/** English display copy. Korean category identifiers and user content stay intact. */
export const englishCopy: Record<string, string> = {
  멕시칸: "Mexican",
  데이트코스: "Date Night",
  혼밥: "Solo Dining",
  펍나이트: "Pub Night",
  브런치: "Brunch",
  가성비: "Great Value",
  "혼자 여행": "Solo Trip",
  "전시/문화": "Arts & Culture",
  액티비티: "Activities",
  "맛집 투어": "Food Tour",
  "나이스 오렌지": "Nice Orange",
  "오렌지 체크와 스마일 장식이 있는 먼치 프레임이에요.":
    "A Munchie frame with orange checks and smiley decorations.",
  "데이트 · 소풍 · 기분 좋은 하루": "Dates · picnics · happy days",
  "럭키 그린": "Lucky Green",
  "네잎클로버와 무지개가 가득한 lucky day 프레임이에요.":
    "A lucky-day frame filled with clovers and rainbows.",
  "옐로우 노트": "Yellow Note",
  "노란 패브릭과 종이 조각이 겹쳐진 포근한 프레임이에요.":
    "A cozy frame layered with yellow fabric and paper scraps.",
  "브런치 · 카페 · 따뜻한 하루": "Brunch · cafes · cozy days",
  "러블리 라벤더": "Lovely Lavender",
  "라벤더 체크와 파스텔 리본이 있는 러블리 프레임이에요.":
    "A lovely frame with lavender checks and pastel ribbons.",
  "감성 코스 · 북카페 · 조용한 하루": "Cozy courses · book cafes · quiet days",
  "딸기 피크닉": "Strawberry Picnic",
  "딸기와 버튼 장식이 가득한 피크닉 프레임이에요.":
    "A picnic frame filled with strawberries and button decorations.",
  "디저트 투어 · 카페 · 달콤한 코스": "Dessert tours · cafes · sweet stops",
  "해피 핑크": "Happy Pink",
  "Be happy! 스마일과 별이 톡톡 튀는 팝 핑크 프레임이에요.":
    "A bright pink frame with smiles, stars and a Be Happy message.",
  "액티비티 · 생일 · 신나는 코스": "Activities · birthdays · fun courses",
  "소프트 블루": "Soft Blue",
  "파스텔 블루와 라벤더 조각이 섞인 기록장 프레임이에요.":
    "A journal frame with pastel blue and lavender scraps.",
  "혼자 여행 · 전시 · 시티 투어": "Solo trips · exhibitions · city tours",
  "레드 체크": "Red Check",
  "레드 체크와 리본, 클로버가 어우러진 피크닉 프레임이에요.":
    "A picnic frame with red checks, ribbons and clovers.",
  "맛집 투어 · 브런치 · 레트로 감성": "Food tours · brunch · retro vibes",
  "굿데이 블루": "Good Day Blue",
  "GOOD DAY 티켓과 데님 별 장식이 있는 차분한 블루 프레임이에요.":
    "A calm blue frame with Good Day tickets and denim stars.",
  "산책 · 기록 · 여유로운 하루": "Walks · journals · relaxed days",
  "프레시 레인보우": "Fresh Rainbow",
  "알록달록한 종이 조각과 스티커가 밝게 둘러진 먼치 프레임이에요.":
    "A bright Munchie frame with colorful paper scraps and stickers.",
  "친구 모임 · 생일 · 즐거운 기록": "Friends · birthdays · happy memories",
  "스토리 디자인을 4:3 맛집 피드에 맞게 재구성했어요.":
    "A story design adapted for 4:3 food posts.",
  "맛집 기록 · 사진 앨범 · Munchie 피드":
    "Food memories · photo albums · Munchie posts",
  "참치마요 주먹밥": "Tuna Mayo Rice Ball",
  "먼치 피드 기록 보상": "Munchie Post Reward",
  "딸기 한입 케이크": "Strawberry Cake Bite",
  "따끈한 라멘": "Warm Ramen",
  "알록달록 초밥": "Colorful Sushi",
  "치즈 듬뿍 피자": "Cheesy Pizza",
  "바삭한 타코": "Crispy Taco",
  "미니 치즈버거": "Mini Cheeseburger",
  "싱그러운 샐러드": "Fresh Salad",
  "코랄 후드티": "Coral Hoodie",
  "노랑 레인코트": "Yellow Raincoat",
  "스트로베리 피크닉": "Strawberry Picnic",
  "블루 세일러복": "Blue Sailor Outfit",
  "베이커리 에이프런": "Bakery Apron",
  "민트 코티지 가디건": "Mint Cottage Cardigan",
  "데님 플레이 오버롤": "Denim Play Overalls",
  "라일락 드림 파자마": "Lilac Dream Pajamas",
  "체리 바시티": "Cherry Varsity",
  "스페이스 익스플로러": "Space Explorer",
  "리틀 아티스트 스목": "Little Artist Smock",
  "가든 헬퍼 오버롤": "Garden Helper Overalls",
  "코지 디텍티브 케이프": "Cozy Detective Cape",
  "코랄 베레모": "Coral Beret",
  "깅엄 리본": "Gingham Ribbon",
  "네이비 세일러 캡": "Navy Sailor Cap",
  "크림 셰프 퍼프": "Cream Chef Hat",
  "개구리 버킷햇": "Frog Bucket Hat",
  "크림 백리본": "Cream Back Ribbon",
  "네이비 사이드 리본": "Navy Side Ribbon",
  "라일락 나이트캡": "Lilac Nightcap",
  "핑크 루프 리본": "Pink Loop Ribbon",
  "페리윙클 스페이스 후드": "Periwinkle Space Hood",
  "틸 베레모": "Teal Beret",
  "코랄 튤립 헤드밴드": "Coral Tulip Headband",
  "포레스트 디텍티브 캡": "Forest Detective Cap",
  "검정 동그란 안경": "Black Round Glasses",
  "코랄 하트 안경": "Coral Heart Glasses",
  "코코아 클래식 선글라스": "Cocoa Classic Sunglasses",
  "허니 스타 선글라스": "Honey Star Sunglasses",
  "라일락 캣아이 선글라스": "Lilac Cat-eye Sunglasses",
  "초록 백팩": "Green Backpack",
  "피크닉 바스켓": "Picnic Basket",
  "네이비 앵커 파우치": "Navy Anchor Pouch",
  "바게트 토트": "Baguette Tote",
  "구름 파우치": "Cloud Pouch",
  "도토리 사첼": "Acorn Satchel",
  "카메라 크로스백": "Camera Crossbody Bag",
  "별 파우치": "Star Pouch",
  "체리 크로스백": "Cherry Crossbody Bag",
  "허니 문 파우치": "Honey Moon Pouch",
  "팔레트 크로스백": "Palette Crossbody Bag",
  "테라코타 물뿌리개": "Terracotta Watering Can",
  "돋보기 사첼": "Magnifying Glass Satchel",
  새싹: "Seedling",
  "맛 탐험": "Food Explorer",
  "한상 수집": "Meal Collector",
  "맛추억 마스터": "Food Memory Master",
  "런치메이트 성장": "Lunchmate Growth",
  "블러시 핑크": "Blush Pink",
  "버터 타일": "Butter Tile",
  "빈티지 핀도트": "Vintage Pin Dot",
  "파우더 블루": "Powder Blue",
  "가든 아이보리": "Garden Ivory",
  "모던 라일락": "Modern Lilac",
  "피치 우드": "Peach Wood",
  "허니 우드": "Honey Wood",
  "월넛 우드": "Walnut Wood",
  "라이트 우드": "Light Wood",
  "선룸 스톤": "Sunroom Stone",
  "크림 우드": "Cream Wood",
  "피크닉 수납장": "Picnic Cabinet",
  "미니 키친": "Mini Kitchen",
  "레코드 수납장": "Record Cabinet",
  "블루 공부책상": "Blue Study Desk",
  "가든 쉼터": "Garden Retreat",
  "미니멀 콘솔": "Minimal Console",
  "핑크 피크닉": "Pink Picnic",
  "옐로우 런치": "Yellow Lunch",
  "빈티지 프레임": "Vintage Frame",
  "블루 노트": "Blue Note",
  "플라워 가든": "Flower Garden",
  "모던 미니멀": "Modern Minimal",
  "네컷 베이직": "Four-shot Basic",
  "네컷 컬러": "Four-shot Color",
  "네컷 무드": "Four-shot Mood",
  "로드맵 체리": "Roadmap Cherry",
  "로드맵 포토": "Roadmap Photo",
  "로드맵 피크닉": "Roadmap Picnic",
  "로드맵 빈티지": "Roadmap Vintage",
  "로드맵 컬러": "Roadmap Color",
  "런치 트레이 레드": "Lunch Tray Red",
  "런치 트레이 블루": "Lunch Tray Blue",
  "런치 트레이 피크닉": "Lunch Tray Picnic",
  "CD 핑크": "CD Pink",
  "CD 컬러": "CD Color",
  "CD 스크랩": "CD Scrapbook",
  "영수증 모노": "Receipt Mono",
  "영수증 빈티지": "Receipt Vintage",
  "영수증 컬러": "Receipt Color",
  "티켓 클래식": "Ticket Classic",
  "티켓 로맨틱": "Ticket Romantic",
  "ZIP 디자인 · 사진 위치 편집 가능": "ZIP Design · Editable Photo Positions",
  "옐로우 먼치트레이": "Yellow Munchie Tray",
  직선거리: "Straight-line Distance",
  사용자: "User",
  "피드를 불러오지 못했어요.": "Couldn't load the feed.",
  "점심 세션": "Lunch Session",
  "세션 자격 증명을 받지 못했어요.": "Couldn't obtain session credentials.",
  지민: "Jimin",
  "오늘의 한 끼를 기록해요.": "Capturing today's meal.",
  제니: "Jenny",
  "카페와 디저트를 좋아해요.": "A fan of cafes and desserts.",
  민수: "Minsu",
  "주말 브런치를 찾아다녀요.": "Always looking for weekend brunch.",
  하늘: "Haneul",
  "동네 맛집을 공유해요.": "Sharing neighborhood food spots.",
  도윤: "Doyun",
  "퇴근 후 한 잔 코스를 좋아해요.": "A fan of after-work drinks.",
  서아: "Seoa",
  "맛있는 순간을 모아요.": "Collecting delicious moments.",
  "DODAM 다녀왔어요. dumplings · tteokbokki 진짜 맛있었다 👍":
    "Visited DODAM. The dumplings and tteokbokki were delicious 👍",
  "Time after time 다녀왔어요. latte · cappuccino 진짜 맛있었다 👍":
    "Visited Time after time. Loved the latte and cappuccino 👍",
  "O3 Brunswick 다녀왔어요. cinnamon roll · almond croissant 진짜 맛있었다 👍":
    "Visited O3 Brunswick. Loved the cinnamon roll and almond croissant 👍",
  "trbl. Coffee 다녀왔어요. coffee · croissant 진짜 맛있었다 👍":
    "Visited trbl. Coffee. Loved the coffee and croissant 👍",
  "CATALOGUE 다녀왔어요. latte · coffee 진짜 맛있었다 👍":
    "Visited CATALOGUE. Loved the latte and coffee 👍",
  "Brunetti Classico 다녀왔어요. desserts · cakes 진짜 맛있었다 👍":
    "Visited Brunetti Classico. Loved the desserts and cakes 👍",
  "seoul tiger 다녀왔어요. burger · fries 진짜 맛있었다 👍":
    "Visited seoul tiger. Loved the burger and fries 👍",
  "Leonardo's Pizza Palace 다녀왔어요. pizza 진짜 맛있었다 👍":
    "Visited Leonardo's Pizza Palace. The pizza was delicious 👍",
  "GAMJA HOTTEOK 다녀왔어요. hotteok 진짜 맛있었다 👍":
    "Visited GAMJA HOTTEOK. The hotteok was delicious 👍",
  "Good Measure 다녀왔어요. grilled meat · bread 진짜 맛있었다 👍":
    "Visited Good Measure. Loved the grilled meat and bread 👍",
  "OMI380 다녀왔어요. waffle · matcha_ice_cream 진짜 맛있었다 👍":
    "Visited OMI380. Loved the waffle and matcha ice cream 👍",
  "ANGUS & BON 다녀왔어요. steak · pasta 진짜 맛있었다 👍":
    "Visited ANGUS & BON. Loved the steak and pasta 👍",
  "맛있는 하루 코스": "A Delicious Day",
  "맛있는 하루의 기록 😋": "Memories of a Delicious Day 😋",
  "맛있는 곳들로 꽉 채운 하루, 너무 완벽해!":
    "A day full of delicious places — just perfect!",
  점심부터_바까지: "lunch_to_drinks",
  맛집_투어: "food_tour",
  성수동: "Seongsu",
  "온더보더 성수점": "On the Border Seongsu",
  점심: "Lunch",
  "맛있는 타코와 파히타!": "Delicious tacos and fajitas!",
  "어니언 성수": "Onion Seongsu",
  "소금빵은 필수!": "The salt bread is a must!",
  대림창고: "Daelim Changgo",
  "창고 감성 브런치": "Warehouse-style brunch",
  "연남동 데이트 코스": "Yeonnam Date Course",
  데이트: "Date",
  연남동: "Yeonnam",
  카페투어: "Cafe Tour",
  "미리보기 요청이 잠시 실패했어요. 선택한 음식으로 다시 시도해 주세요.":
    "Preview failed temporarily. Try again with your selected food.",
  "맛있는 한입! +": "A delicious bite! +",
  "미리보기 요청에 실패했어요. 음식은 차감되지 않았으니 다시 시도해 주세요.":
    "Preview failed. Your food wasn't used. Please try again.",
  "프로필 피드를 불러오지 못했어요.": "Couldn't load the profile feed.",
  "피드 형식이 올바르지 않아요.": "Invalid feed format.",
  김민지: "Minji Kim",
  "Lunchie 사용자": "Lunchie User",
  베이커리: "Bakery",
  이탈리안: "Italian",
  일식: "Japanese",
  중식: "Chinese",
  한식: "Korean",
  레스토랑: "Restaurant",
  중동: "Middle Eastern",
  말레이시안: "Malaysian",
  양식: "Western",
  타이: "Thai",
  베트남: "Vietnamese",
  "이미지를 편집용으로 불러오지 못했습니다.":
    "Couldn't load the image for editing.",
  "사진 편집을 지원하지 않는 브라우저입니다.":
    "This browser doesn't support photo editing.",
  "님이 참여했어요!": " joined!",
  "참여자를 기다리고 있어요. 현재": "Waiting for participants. Currently ",
  "님만 투표를 시작할 수 있어요.": " can start the vote.",
  "투표를 시작하려면 최소": "Voting needs at least ",
  "명이 필요해요.": " people.",
  "진행 중": "In Progress",
  "든든한 한식": "Korean Comfort Food",
  "밥 · 찌개 · 고기": "Rice · stews · meat",
  아시안: "Asian",
  "면 · 딤섬 · 일식": "Noodles · dim sum · Japanese",
  "양식·브런치": "Western & Brunch",
  "파스타 · 카페 · 베이커리": "Pasta · cafes · bakeries",
  "오늘의 랜덤": "Surprise Me",
  "추천 순서 그대로": "Keep the recommended order",
  "날짜 정보 준비 중": "Date unavailable",
  "명 최종 투표": " final voters",
  "명 LIKE": " likes",
  "페스코 채식": "Pescatarian",
  "글루텐 프리": "Gluten-free",
  돼지고기: "Pork",
  소고기: "Beef",
  양고기: "Lamb",
  해산물: "Seafood",
  "갑각류·조개류": "Shellfish",
  견과류: "Nuts",
  유제품: "Dairy",
  달걀: "Eggs",
  "평가 없음": "Not Rated",
  "상세 정보 준비 중이에요.": "Details coming soon.",
  "알 수 없는 오류가 발생했어요.": "An unexpected error occurred.",
  "응답이 비어있어요.": "The response was empty.",
  "로그인 세션이 없습니다.": "No signed-in session.",
  "프로필을 불러오지 못했습니다.": "Couldn't load the profile.",
  "로그인 후 사용자를 검색할 수 있어요.": "Sign in to search for users.",
  "팔로우하지 못했습니다.": "Couldn't follow this user.",
  "팔로우를 취소하지 못했습니다.": "Couldn't unfollow this user.",
  "팔로우 상태를 불러오지 못했습니다.": "Couldn't load follow status.",
  "팔로우 수를 불러오지 못했습니다.": "Couldn't load follow counts.",
  "팔로우 목록을 불러오지 못했습니다.": "Couldn't load the follow list.",
  "식당 정보를 불러오지 못했어요.": "Couldn't load restaurant details.",
  "선택을 저장하지 못했어요.": "Couldn't save your choice.",
  "최종 선택이 아직 세션에 반영되지 않았어요.":
    "Your final choice hasn't been recorded yet.",
  "한입 새싹": "Budding Foodie",
  "기본 런치 스티커 placeholder": "Default Lunch Sticker Placeholder",
  "맛 탐험가": "Food Explorer",
  "피크닉 냅킨 아이템 placeholder": "Picnic Napkin Placeholder",
  "한상 수집가": "Meal Collector",
  "미니 접시 아이템 placeholder": "Mini Plate Placeholder",
  "반짝 포크 아이템 placeholder": "Shiny Fork Placeholder",
  "꾸미기 아이템": "Customization Items",
  페스코: "Pescatarian",
  "돼지고기 제외": "No Pork",
  "소고기 제외": "No Beef",
  "양고기 제외": "No Lamb",
  "갑각류·조개류 제외": "No Shellfish",
  "견과류 제외": "No Nuts",
  "유제품 제외": "No Dairy",
  "달걀 제외": "No Eggs",
  육식: "Meat Lover",
  "로그인이 필요합니다.": "Sign-in is required.",
  "JPEG, PNG, WebP 이미지만 업로드할 수 있습니다.":
    "Only JPEG, PNG and WebP images can be uploaded.",
  "이미지는 4MB 이하여야 합니다.": "Images must be 4 MB or smaller.",
  "로컬 사용자 스키마를 갱신한 뒤 프로필을 수정할 수 있습니다.":
    "Update the local user schema before editing profiles.",
  "변경할 프로필 정보가 없습니다.": "No profile changes provided.",
  "내가 업로드한 프로필 사진만 사용할 수 있습니다.":
    "You can only use a profile photo you've uploaded.",
  "이름은 1~80자로 입력해 주세요.": "Names must be 1–80 characters.",
  "이미 사용 중인 아이디입니다.": "This handle is already taken.",
  "식단 설정 형식이 올바르지 않습니다.": "Invalid dietary preference format.",
  "지원하지 않는 식단 설정이 포함되어 있습니다.":
    "Some dietary preferences aren't supported.",
  "관리자 로그인이 필요합니다.": "Admin sign-in is required.",
  "관리자 권한이 없습니다.": "Admin access is required.",
  "사진 식별자가 올바르지 않습니다.": "Invalid photo ID.",
  "사진을 찾을 수 없습니다.": "Photo not found.",
  "검수 내용이 올바르지 않습니다.": "Invalid review details.",
  "자기 자신은 팔로우할 수 없습니다.": "You can't follow yourself.",
  "사용자를 찾을 수 없습니다.": "User not found.",
  "제목과 1~3개의 장소가 필요합니다.": "A title and 1–3 places are required.",
  "장소 정보가 올바르지 않습니다.": "Invalid place details.",
  "존재하지 않는 장소가 포함되어 있습니다.": "One or more places don't exist.",
  "포스팅하려면 배치한 사진을 1장 이상 저장해야 합니다.":
    "Save at least one placed photo before posting.",
  "사진은 이 코스에 포함된 식당에만 연결할 수 있습니다.":
    "Photos can only be linked to restaurants in this course.",
  "게시물 정보가 필요합니다.": "Post details are required.",
  "게시물을 찾을 수 없습니다.": "Post not found.",
  "식당과 멱등성 키가 필요합니다.":
    "A restaurant and idempotency key are required.",
  "식당을 찾을 수 없습니다.": "Restaurant not found.",
  "거리 제한을 사용하려면 현재 위치 권한이 필요합니다. 거리 제한 없음을 선택하면 위치 없이 시작할 수 있어요.":
    "Enable location to use a radius limit, or choose no radius limit to continue without location.",
  "세션을 서버에 저장하지 못했습니다.": "Couldn't save the session.",
  "초대 코드를 만들지 못했습니다.": "Couldn't create an invite code.",
  "참여자 정보가 필요합니다.": "Participant details are required.",
  "세션을 찾을 수 없거나 만료되었습니다.": "Session not found or expired.",
  "이미 종료된 세션입니다.": "This session has ended.",
  "이미 투표가 시작된 세션입니다.": "Voting has already started.",
  "이 기기의 세션 자격 증명을 확인할 수 없습니다.":
    "Couldn't verify this device's session credentials.",
  "호스트가 혼자 세션으로 만들었어요. 호스트가 '같이' 세션을 새로 만들어야 합니다.":
    "The host created a solo session. They need to create a group session to invite others.",
  "정원이 찼어요.": "This session is full.",
  "사용자 정보가 필요합니다.": "User details are required.",
  "세션을 찾을 수 없습니다.": "Session not found.",
  "세션 취소는 호스트만 할 수 있습니다.":
    "Only the host can cancel this session.",
  "호스트 자격 증명을 확인할 수 없습니다.": "Couldn't verify host credentials.",
  "호스트는 세션을 취소해야 합니다.":
    "The host must cancel the session instead of leaving.",
  "참여자 자격 증명을 확인할 수 없습니다.":
    "Couldn't verify participant credentials.",
  "준비 상태 정보가 필요합니다.": "Ready status is required.",
  "대기 중인 세션에서만 준비 상태를 바꿀 수 있습니다.":
    "Ready status can only change while waiting.",
  "세션 참여자를 찾을 수 없습니다.": "Session participant not found.",
  "세션 상태가 필요합니다.": "Session status is required.",
  "지원하지 않는 세션 상태입니다.": "Unsupported session status.",
  "세션 시작은 호스트만 할 수 있습니다.":
    "Only the host can start the session.",
  "종료되거나 취소된 세션은 시작할 수 없습니다.":
    "Ended or cancelled sessions can't be started.",
  "명이 필요합니다.": " participants.",
  "식당 후보를 준비하지 못했습니다.": "Couldn't prepare restaurant options.",
  "반경 안에 현재 조건과 맞는 식당이 없어요. 반경 또는 조건을 바꿔 주세요.":
    "No matching restaurants within this radius. Adjust your radius or preferences.",
  "현재 조건과 맞는 식당이 없어요. 조건을 바꿔 주세요.":
    "No matching restaurants. Adjust your preferences.",
  "올바른 스와이프 정보가 필요합니다.": "Valid swipe details are required.",
  "유효하지 않은 투표입니다.": "Invalid vote.",
  "올바른 진행 정보가 필요합니다.": "Valid progress details are required.",
  "게시물과 한줄평을 입력해주세요.": "A post and short review are required.",
  "수정 권한이 없습니다.": "You don't have permission to edit this.",
  "승계할 서버 사진 배치가 없습니다.": "No server photo layout to inherit.",
  "이 게시물을 삭제할 권한이 없습니다.":
    "You don't have permission to delete this post.",
  "게시물과 댓글 내용을 입력해주세요.": "A post and comment text are required.",
  "답글을 달 댓글을 찾을 수 없습니다.":
    "The comment you're replying to wasn't found.",
  "신고 대상이 올바르지 않습니다.": "Invalid report target.",
  "포함 확률": "Inclusion Probability",
  "요청 맥락": "Request Context",
  "계측 연결 보완 필요": "Instrumentation Needs Attribution",
  "스와이프 수와 별개로 추천 당시의": "Recommendation-time ",
  "기록이 98% 기준에 미달합니다.": " coverage is below 98%.",
  "누락 계측을 먼저 연결한 뒤 표본 수를 판단하세요.":
    "Resolve missing attribution before evaluating sample size.",
  "계측 중 — 표본 축적 필요": "Instrumented — More Samples Needed",
  "서빙 증거는 연결됐지만 개인화 또는 정책 우열을 판단할 표본이 아직 작습니다.":
    "Serving evidence is linked, but samples are too small to evaluate personalization or policy performance.",
  "학습 연결 스와이프": "Attributed swipes: ",
  "건, 최종 결정": "; final decisions: ",
  "건을 모으세요.": " needed.",
  "측정 가능 — 온라인 학습 전": "Measurable — Before Online Learning",
  "정책별 기초 수락률과 카테고리 노출 편향을 볼 수 있습니다. 아직 자동 가중치 변경은 하지 않습니다.":
    "Basic policy acceptance and category exposure bias can be measured. Weights aren't adjusted automatically yet.",
  "고정 정책의 홀드아웃을 유지한 채 오프라인 평가를 먼저 실행하세요.":
    "Run offline evaluation first while retaining a fixed-policy holdout.",
  "오프라인 평가 준비": "Ready for Offline Evaluation",
  "노출 증거와 반응 표본이 있어 IPS/정책 비교를 시작할 수 있습니다. 이는 자동 배포 승인이 아닙니다.":
    "Impression evidence and response samples support IPS and policy comparisons. This doesn't authorize automatic deployment.",
  "사전 등록한 가드레일(결정 시간·재추천·다양성)과 함께 정책 후보를 평가하세요.":
    "Evaluate policies with predefined limits for decision time, rerolls and diversity.",
  "위치와 반경은 유효한 좌표 및 1~50km 값이어야 합니다.":
    "Use valid coordinates and a radius of 1–50 km.",
  "음식점·카페·마켓 같은 먹거리 장소만 코스에 담을 수 있어요.":
    "Only food venues such as restaurants, cafes and markets can be added to courses.",
  마켓: "Market",
  바: "Bar",
  테이크아웃: "Takeaway",
  "는 필수 문자열입니다.": " must be a non-empty string.",
  "가 너무 깁니다.": " is too long.",
  "는 문자열이어야 합니다.": " must be a string.",
  "Google 장소 검색 서버 설정이 필요합니다.":
    "Google Places server configuration is required.",
  "Google 장소 서비스를 불러오지 못했어요.": "Couldn't access Google Places.",
  "선택한 장소의 위치를 찾지 못했어요.":
    "Couldn't find the selected place's location.",
  "이름 없음": "Unnamed",
  "식당 정보를 저장하지 못했어요.": "Couldn't save restaurant details.",
  "경로는 장소 2~10곳이 필요해요.": "A route needs 2–10 places.",
  "경로를 가져오지 못했어요.": "Couldn't load the route.",
  "경로 폴리라인이 비어 있어요.": "The route polyline is empty.",
  "장소 검색 중 오류가 발생했어요.":
    "An error occurred while searching places.",
  "변경할 검수 항목이 없습니다.": "No review changes provided.",
  "검수 상태가 올바르지 않습니다.": "Invalid review status.",
  "사진 종류가 올바르지 않습니다.": "Invalid photo type.",
  "인물 포함 여부가 올바르지 않습니다.": "Invalid people flag.",
  "품질 점수는 0부터 1 사이여야 합니다.":
    "Quality scores must be between 0 and 1.",
  "검수 메모가 올바르지 않습니다.": "Invalid review notes.",
  "검수 메모는 500자 이하여야 합니다.":
    "Review notes must be 500 characters or fewer.",
  "slate_id (노출·스와이프 연결)": "slate_id (impression/swipe attribution)",
  "propensity 승계 (스와이프)": "Propensity Attribution (Swipes)",
  "안정적 user_id": "Stable user_id",
  "-- 메뉴·사진 반영 (": "-- Menu and photo update (",
  "곳, 메뉴": " restaurants, menus ",
  "개 요리 · 사진": " dishes · photos ",
  "곳) — D1 마이그레이션으로 적용": " restaurants) — apply as a D1 migration",
  "멜버른 CBD 커피 & 레인웨이": "Melbourne CBD Coffee & Laneways",
  "멜버른 커피 문화의 정수를 맛보는 도심 레인웨이 산책 코스.":
    "A city laneway walk celebrating Melbourne's coffee culture.",
  "플린더스 레인 미식 투어": "Flinders Lane Food Tour",
  "브런치부터 타파스, 모던 타이까지 플린더스 레인을 따라가는 맛집 코스.":
    "Follow Flinders Lane for brunch, tapas and modern Thai dining.",
  "피츠로이 하루 종일 코스": "A Full Day in Fitzroy",
  "커피, 크루아상, 젤라또, 그리고 파인다이닝까지 — 피츠로이를 온전히 즐기는 풀데이 코스.":
    "Explore Fitzroy through coffee, croissants, gelato and fine dining.",
  "피츠로이 디저트 & 비건": "Fitzroy Desserts & Vegan Dining",
  "달콤한 크루아상과 젤라또, 식물성 디너로 마무리하는 가벼운 저녁 코스.":
    "Croissants and gelato followed by a plant-based dinner.",
  "CBD → 피츠로이 크로스 데이트": "CBD to Fitzroy Date",
  "도심 커피로 시작해 모던 타이 점심, 콜링우드 카페, 거트루드 파인다이닝으로 이어지는 하루 데이트.":
    "Start with city coffee, then enjoy Thai lunch, Collingwood cafes and Gertrude Street dining.",
  "서울 in 멜버른: 한식 코스": "Seoul in Melbourne: Korean Food",
  "숯불 바비큐부터 양념치킨까지, 멜버른에서 즐기는 진짜 한식 투어.":
    "Explore Korean dining in Melbourne, from charcoal barbecue to seasoned fried chicken.",
  "차이나타운 딤섬 & 광둥 코스": "Chinatown Dim Sum & Cantonese Dining",
  "멜버른 차이나타운에서 샤오롱바오, 미슐랭 딤섬, 심야 광둥식까지.":
    "Explore Melbourne Chinatown through soup dumplings, dim sum and late-night Cantonese dining.",
  "멜버른 이자카야 & 오마카세": "Melbourne Izakaya & Omakase",
  "모던 아시안 다이닝으로 시작해 이자카야, 그리고 프리미엄 스시 오마카세로.":
    "Enjoy modern Asian dining, izakaya and premium sushi omakase.",
  "파스타·피자 이탈리안 코스": "Italian Pasta & Pizza Course",
  "수제 파스타, 클래식 에스프레소 바, 나폴리 피자로 이어지는 이탈리안 미식.":
    "An Italian food journey through handmade pasta, espresso and Neapolitan pizza.",
  "저기압일 땐 고기 앞으로": "Meat for a Mood Boost",
  "기분이 가라앉는 날엔 역시 고기. 숯불 한우, 아르헨티나 아사도, 코리안 BBQ에 파인다이닝 고기까지 — 고기로 시작해 고기로 끝나는 날.":
    "A hearty day of charcoal barbecue, Argentinian asado, Korean BBQ and fine dining.",
  "탄수화물은 죄가 없다": "Carbs without Guilt",
  "크루아상으로 시작해 파스타, 피자로 달리는 무한 탄수화물 코스. 다이어트는 내일부터.":
    "Start with croissants and continue through pasta and pizza. A delicious day of carbs.",
  "robots.txt 차단": "Blocked by robots.txt",
  "정원이 찼어요": "Session Full",
  베지테리언: "Vegetarian",
  유제품프리: "Dairy-free",
  코셔: "Kosher",
  넛프리: "Nut-free",
  "이전 메뉴": "Previous Menu Item",
  "다음 메뉴": "Next Menu Item",
  "상세 설명은 준비 중이에요": "Details coming soon",
  "← 이전 / 다음 메뉴 → ·": "← Previous / Next Item → · ",
  "검수 대기": "Pending Review",
  승인: "Approve",
  제외: "Exclude",
  "단일 음식": "Single Dish",
  "테이블 음식": "Table of Food",
  실내: "Interior",
  외관: "Exterior",
  기타: "Other",
  미분류: "Uncategorized",
  "이미지 검수 내용을 저장하지 못했습니다.": "Couldn't save the photo review.",
  "이미지를 불러올 수 없음": "Couldn't Load Image",
  "검수 이미지": " review image",
  "인물 포함": "Contains People",
  "사진 종류": "Photo Type",
  "품질 0–1": "Quality 0–1",
  "품질 점수": "Quality Score",
  "검수 메모": "Review Notes",
  "감지 음식:": "Detected dishes: ",
  "이미지 검수 목록을 불러오지 못했습니다.": "Couldn't load photo reviews.",
  "식당 이미지 검수": "Restaurant Photo Review",
  "원본 보유 여부와 별개로, 런치 카드에 안전하게 쓸 수 있는 서로 다른 음식 사진을 식당별로 관리합니다.":
    "Manage distinct food photos suitable for Lunchie cards, separately from source-photo availability.",
  "식당명 또는 주소 검색": "Search restaurant names or addresses",
  검색: "Search",
  "추천 가능": "Ready to Recommend",
  "서로 다른 안전 사진 2장 이상": "At least 2 distinct eligible photos",
  "보강 필요": "Needs More Photos",
  "추천 기준 미달": "Below Recommendation Requirements",
  "추천용 음식 사진 없음": "No Eligible Food Photos",
  "원본이 없어졌다는 뜻이 아님": "Original photos may still exist",
  "추천용 1장뿐": "Only 1 Eligible Photo",
  "다른 음식 사진 1장 필요": "Needs another distinct food photo",
  "추천 준비도 필터": "Recommendation Readiness",
  "전체 식당": "All Restaurants",
  "전체 이미지": "All Photos",
  "개 식당": " restaurants",
  "모든 사진 종류": "All Photo Types",
  "검색 결과": "Search results: ",
  "이전 이미지 페이지": "Previous Photo Page",
  "다음 이미지 페이지": "Next Photo Page",
  "이미지 목록을 불러오는 중…": "Loading photos…",
  "추천용 사진 보강 필요": "More Eligible Photos Needed",
  "추천용 서로 다른 사진": "Distinct eligible photos: ",
  "장 · 최소": " photos · minimum ",
  "현재 페이지": "Current page: ",
  "조건에 맞는 식당 이미지가 없습니다.":
    "No restaurant photos match these filters.",
  "Google 로그인을 시작하지 못했어요.": "Couldn't start Google sign-in.",
  "계정에 로그인": "Sign In to Your Account",
  "기기를 바꿔도 프로필과 팔로우 관계를 이어갈 수 있어요.":
    "Keep your profile and follows across devices.",
  "Google로 계속하기": "Continue with Google",
  "Google 프로필": "Google Profile",
  "Google 사용자": "Google User",
  "이메일 정보 없음": "No Email Available",
  "Google 계정으로 로그인됨": "Signed in with Google",
  "로그아웃하고 새 익명 세션으로 전환할까요?":
    "Sign out and start a new guest session?",
  "로그아웃했어요. 익명 모드로 계속 사용할 수 있어요.":
    "Signed out. You can continue as a guest.",
  "로그아웃하지 못했어요.": "Couldn't sign out.",
  "Lunchie Munchie를 준비하고 있어요…": "Getting Lunchie Munchie ready…",
  "기존 계정 로그인을 시작하지 못했어요.":
    "Couldn't sign in to your existing account.",
  "기기를 바꿔도 계정과 팔로우 관계를 이어갈 수 있어요.":
    "Keep your account and follows across devices.",
  "익명 계정에 Google을 연결하면 현재 uid와 팔로우 관계가 유지됩니다.":
    "Linking Google to your guest account keeps your current ID and follows.",
  "이미 가입된 Google 계정이에요": "This Google Account Is Already Registered",
  "기존 계정으로 로그인하면 현재 익명 계정의 로컬 데이터와 소유권은 자동으로 옮겨지지 않아요.":
    "Signing in to an existing account doesn't automatically transfer guest data or ownership.",
  "기존 계정으로 로그인": "Sign In to Existing Account",
  "지도에서 선택": "Select on Map",
  "피드 검색 기준 위치": "Feed Search Location",
  "팔로우 상태를 바꾸지 못했어요. 잠시 후 다시 시도해 주세요.":
    "Couldn't update your follow. Please try again shortly.",
  언팔로우: "Unfollow",
  팔로우: "Follow",
  "목록에서 프로필을 열거나 팔로우 상태를 바꿀 수 있어요.":
    ": view profiles and manage follows.",
  "불러오는 중…": "Loading…",
  "목록이 비어 있어요.": " list is empty.",
  "마감 전": "Before Deadline",
  초: " sec",
  "Lunchie 결과가 나왔어요!": "Lunchie Results Are Ready!",
  "이번에는 합의가 어려웠어요": "No Agreement This Time",
  "결승전 투표가 열렸어요!": "Final Voting Is Open!",
  "새로운 후보가 도착했어요!": "New Options Are Here!",
  "친구들의 결승 선택을 모으는 중이에요": "Collecting everyone's final choices",
  "런치 투표": "Lunch Vote",
  남았어요: " left",
  "눌러서 결과를 확인해요": "Tap to See Results",
  "눌러서 투표 페이지로 돌아가요": "Tap to Return to Voting",
  "친구들이 고르는 동안 내 런치킨을 만나봐요":
    "Spend time with your Lunchkin while friends choose",
  "콕! 런치 투표는 내가 지켜보고 있어요":
    "I'm keeping an eye on your lunch vote!",
  "기다림 도우미 런치킨과 상호작용": "Interact with your waiting companion",
  "런치 투표를 알려주는 런치킨": "Lunchkin vote notifications",
  "식당 상세정보 닫기": "Close Restaurant Details",
  상세정보: " Details",
  "아래로 내려 닫거나 뒤로가기를 사용할 수 있어요":
    "Swipe down or go back to close",
  "상세정보 닫기": "Close Details",
  "상세 정보": "Details",
  "최신 식당 정보를 확인하는 중…": "Loading the latest restaurant details…",
  "빠른 매칭 취소": "Cancel Quick Match",
  "대기방 나가기": "Leave Lobby",
  "요청을 처리하지 못했어요. 다시 시도해 주세요.":
    "Couldn't complete the request. Please try again.",
  "빠른 매칭 관리": "Manage Quick Match",
  "빠른 매칭을 취소할까요?": "Cancel Quick Match?",
  "대기방에서 나갈까요?": "Leave the Lobby?",
  "대기방의 모든 참여자가 나가게 되며 이 세션은 다시 시작할 수 없어요.":
    "This will end the session for everyone. It can't be restarted.",
  "나만 빠른 매칭에서 나가며 다른 참여자의 세션은 계속 유지돼요.":
    "You'll leave Quick Match. Other participants can continue.",
  "이 기기에 저장된 세션 지우기": "Clear Session on This Device",
  "세션 유지": "Keep Session",
  "계속 참여": "Stay",
  "나의 최종 선택": "My Final Choice",
  "친구들과 함께 고른 최종 선택": "Our Final Choice",
  "Lunchie 결과 공유 카드": " Lunchie share card",
  "Lunchie 런치킨": "Lunchie Lunchkin",
  "오늘의 Lunchie Pick": "Today's Lunchie Pick",
  "참여자 정보 없음": "No Participant Information",
  "대표 메뉴": "Signature Dishes",
  지역: "Area",
  날짜: "Date",
  "친구들과 같이 고른 오늘의 한 끼 · Lunchie Munchie":
    "Today's meal, chosen together · Lunchie Munchie",
  ", 선택됨": ", selected",
  주먹밥: "Rice Ball",
  식빵: "Bread",
  만두: "Dumplings",
  도넛: "Donut",
  라멘: "Ramen",
  딸기: "Strawberry",
  아보카도: "Avocado",
  새우튀김: "Shrimp Tempura",
  알: "Egg",
  "새싹 푸디": "Budding Foodie",
  "먹보 푸디": "Hungry Foodie",
  "전설의 미식가": "Legendary Foodie",
  "냠냠 😋": "Yum Yum 😋",
  "코스맵 더 줘!": "More course maps, please!",
  "맛집 가고 싶다…": "Let's find something delicious…",
  "먹부림 최고 🍴": "Food adventures are the best 🍴",
  "다음 진화까지": "Until the next evolution: ",
  "여기에 놓아주세요!": "Drop It Here!",
  "맛있게 먹는 중…": "Enjoying a bite…",
  "다시 한 번 해볼까?": "Shall we try again?",
  "을 나에게 끌어다 줘!": " — drag it over to me!",
  "새 음식": "New food: ",
  "개 도착! 🍱": " arrived! 🍱",
  "새 음식이 도착했어! 🍱": "New food is here! 🍱",
  "맛추억 미리보기 상세": "Food Memory Preview Details",
  "김밥 EXP": "Gimbap EXP ",
  "런치메이트 룸 열기": "Open Lunchmate Room",
  "개가 있는 런치박스": " items in Lunchbox",
  런치박스: "Lunchbox",
  ", 런치메이트에게 끌어다 놓기": ", drag to your Lunchmate",
  "런치메이트 음식 놓기 영역, 지금 놓을 수 있어요":
    "Lunchmate food drop area, ready to drop",
  "런치메이트 음식 놓기 영역": "Lunchmate Food Drop Area",
  "놀란 런치메이트 캐릭터, 드래그 중": "Surprised Lunchmate while dragging",
  "런치메이트 캐릭터": "Lunchmate Character",
  "런치메이트 대체 표시": "Lunchmate Placeholder",
  키위: "Kiwi",
  사과: "Apple",
  캐릭터: " character",
  "나의 런치박스 🍱": "My Lunchbox 🍱",
  "위아래로 밀어 메뉴를 보고, 탭한 음식은 통째로 끌어주세요.":
    "Browse up and down, then drag a food item.",
  "런치박스 닫기": "Close Lunchbox",
  "한입 나누기 음식 선택": "Choose Food to Share",
  ", 품절": ", unavailable",
  ", 탭하여 선택하거나 런치메이트에게 드래그":
    ", tap to select or drag to your Lunchmate",
  품절: "Unavailable",
  "개 · +": " items · +",
  "↕ 위아래로 밀어 더 많은 음식을 확인하세요": "↕ Scroll to browse more food",
  "한입 준비 중…": "Preparing a bite…",
  "다시 한입 나누기": "Share Another Bite",
  "한입 나누기": "Share a Bite",
  "음식이 캐릭터 옆에 놓이면 끌어다 먹여주세요. 먹인 음식은 1개 차감돼요.":
    "Drag the food next to your Lunchmate to feed it. Each bite uses one item.",
  "새로운 한입이 아직 없어요": "No New Bites Yet",
  "맛있는 기록을 만들면 런치박스에 새로운 음식이 생겨요.":
    "Create food memories to add new items to your Lunchbox.",
  "기록 화면으로 이동하는 기능은 다음 단계에서 연결돼요.":
    "The food journal link is coming soon.",
  "포크와 숟가락을 든 런치킨 캐릭터": "Lunchkin holding a fork and spoon",
  "편안하게 서 있는 런치메이트": "Lunchmate standing calmly",
  "행복한 런치메이트": "Happy Lunchmate",
  "신이 난 런치메이트": "Excited Lunchmate",
  "새 음식에 놀란 런치메이트": "Lunchmate surprised by new food",
  "속상한 런치메이트": "Sad Lunchmate",
  "어떤 음식을 고를지 생각하는 런치메이트": "Lunchmate choosing food",
  "한입을 기다리며 행복해하는 런치메이트":
    "Lunchmate happily waiting for a bite",
  "한입을 받고 기뻐하는 런치메이트": "Lunchmate enjoying a bite",
  "레벨업을 기뻐하며 점프하는 런치메이트":
    "Lunchmate jumping after leveling up",
  "편안하게 서 있는 치킨 런치메이트": "Chicken Lunchmate standing calmly",
  "런치메이트 이미지 대체 표시": "Lunchmate Image Placeholder",
  의상: "Outfit",
  모자: "Hat",
  안경: "Glasses",
  가방: "Bag",
  일반: "Common",
  레어: "Rare",
  스페셜: "Special",
  "새 칭호": "New Title",
  "을 착용한 런치메이트": " outfit on Lunchmate",
  "이번 레벨 보상": "Level Reward",
  "옷장에서 확인할 수 있어요": "Find it in your wardrobe",
  "모든 꾸미기 아이템을 모았어요": "You've Collected Every Item",
  "현재 기기의 미리보기 보상으로 저장됐어요.":
    "Saved as a preview reward on this device.",
  "레벨 정보": "Level Details",
  "음식을 나누고 맛추억을 쌓아 새로운 레벨을 만나보세요.":
    "Share food and collect memories to level up.",
  "맛추억 상세 닫기": "Close Food Memory Details",
  "누적 맛추억": "Total Food Memories",
  "다음 레벨까지": "Until the next level: ",
  "다음 레벨 EXP 진행도": "Next Level EXP Progress",
  "레벨 단계": "Level Stages",
  단계: " stages",
  "아이콘별 레벨 단계": "Level Stages by Icon",
  "다음 레벨에 도달하면 받을 수 있어요.": "Unlock this at the next level.",
  "Lv.1부터 다시 시작": "Restart from Lv.1",
  옷: "Clothes",
  "착용 안 함": "None",
  "레벨업으로 획득": "Earned by Leveling Up",
  "선택 가능": "Available",
  "보유한 아이템을 조합해 런치메이트를 꾸며보세요.":
    "Mix your items to customize your Lunchmate.",
  "선택 중에는 미리보기이며 적용하기를 눌러 저장해요.":
    "Preview your changes, then select Apply to save.",
  "옷장 아이템 종류": "Wardrobe Categories",
  "전체 해제": "Clear All",
  적용하기: "Apply",
  "적용하기를 누른 조합만 프로필에 저장돼요.":
    "Only applied outfits are saved to your profile.",
  "프로필에 적용했어요.": "Applied to your profile.",
  "위쪽 크롭 경계 조절": "Adjust Top Crop Edge",
  "오른쪽 위 크롭 모서리 조절": "Adjust Top-right Crop Corner",
  "오른쪽 크롭 경계 조절": "Adjust Right Crop Edge",
  "오른쪽 아래 크롭 모서리 조절": "Adjust Bottom-right Crop Corner",
  "아래쪽 크롭 경계 조절": "Adjust Bottom Crop Edge",
  "왼쪽 아래 크롭 모서리 조절": "Adjust Bottom-left Crop Corner",
  "왼쪽 크롭 경계 조절": "Adjust Left Crop Edge",
  "왼쪽 위 크롭 모서리 조절": "Adjust Top-left Crop Corner",
  "이 사진은 보안 설정 때문에 크롭 결과를 저장할 수 없어요. 직접 업로드한 사진을 사용해주세요.":
    "Browser security prevents saving this crop. Please use a photo you've uploaded.",
  "사진 편집 취소": "Cancel Photo Editing",
  "사진 크롭": "Crop Photo",
  "프레임을 놓으면 선택 영역이 확대돼요":
    "Release the frame to zoom into your crop",
  "원본 크기로 되돌리기": "Reset to Original Size",
  "크롭할 사진": "Photo to Crop",
  "크롭 영역 이동": "Move Crop Area",
  "자유 비율": "Free Aspect Ratio",
  "사진 적용 중...": "Applying photo…",
  "크롭 적용": "Apply Crop",
  "영업시간 정보 준비 중": "Opening hours unavailable",
  "코스에 등록된 장소예요.": "This place is part of your course.",
  "등록된 메뉴 사진이 없어요.": "No menu photos available.",
  "템플릿 미리보기 닫기": "Close Template Preview",
  "기본 디자인": "Base Design",
  "사진 위치 편집 가능": "Editable Photo Positions",
  "추천 테마": "Suggested Themes",
  벽지: "Wallpaper",
  바닥: "Floor",
  가구: "Furniture",
  소품: "Decor",
  "추천 테마 선택": "Choose Suggested Theme",
  "없음 선택": "Choose None",
  없음: "None",
  "방 꾸미기 카테고리": "Room Decor Categories",
  "템플릿 정보 닫기": "Close Template Details",
  "사진을 넣기 전 기본 양식": "Base Layout without Photos",
  "4:3 규격": "4:3 Format",
  "잘 어울리는 코스": "Best for These Courses",
  "Munchie 피드 배경": "Munchie Post Background",
  "사진은 최대": "Up to ",
  "장까지 배치할 수 있어요.": " photos can be placed.",
  "사진을 불러오지 못했어요.": "Couldn't load the photo.",
  "첫 사진 올리기": "Upload Your First Photo",
  "사진 삭제": "Delete Photo",
  "배치된 사진 선택": "Select Placed Photo",
  "사진을 템플릿에 추가": "Add Photo to Template",
  "새 사진 업로드": "Upload New Photo",
  오늘: "Today",
  "1일 전": "1 day ago",
  "일 전": " days ago",
  "주 전": " weeks ago",
  "로그인 상태를 확인 중이에요. 잠시 후 다시 시도해 주세요.":
    "Checking sign-in. Please try again shortly.",
  "이 기능은 로그인 후 사용할 수 있어요.": "Sign in to use this feature.",
  "댓글을 등록하지 못했어요.": "Couldn't post your comment.",
  "답글을 등록했어요.": "Reply posted.",
  "댓글을 등록했어요.": "Comment posted.",
  "신고를 접수하지 못했어요.": "Couldn't submit your report.",
  "게시물을 신고했어요. 검토 후 필요한 조치를 진행할게요.":
    "Post reported. We'll review it and take action if needed.",
  "게시물과 원본 코스를 삭제했어요.": "Post and original course deleted.",
  "좋아요를 저장하지 못했어요.": "Couldn't save your like.",
  "님의 Munchie 피드": "'s Munchie Post",
  "Munchie 피드를 함께 봐요.": "Check out this Munchie post.",
  "피드 링크를 복사했어요.": "Post link copied.",
  "공유 링크를 복사하지 못했어요.": "Couldn't copy the share link.",
  "게시물 삭제 창 닫기": "Close Post Deletion",
  "게시물과 원본 코스가 영구 삭제되며 복구할 수 없어요.":
    "The post and original course will be permanently deleted. This can't be undone.",
  "게시물 메뉴": "Post Menu",
  "피드 상세 보기": "View Post Details",
  "원본 사진이 없는 이전 게시물": "Older Post without Original Photos",
  "피드 공유하기": "Share Post",
  "게시물 수정": "Edit Post",
  "게시물 삭제": "Delete Post",
  "작성자 보기": "View Author",
  "관리자 삭제": "Delete as Admin",
  "신고 완료": "Reported",
  "게시물 신고": "Report Post",
  "Munchie 피드 이미지 상세 보기": "View Munchie Photo Details",
  "템플릿 보기": "View Template",
  "한줄평 음영 숨기기": "Hide Review Background",
  "한줄평 또렷하게 보기": "Show Review Background",
  "댓글 보기": "View Comments",
  "Munchie 피드를 저장했어요.": "Munchie post saved.",
  "댓글 닫기": "Close Comments",
  댓글: "Comments",
  "댓글창 닫기": "Close Comment Panel",
  "답글 달기": "Reply",
  "댓글 메뉴": "Comment Menu",
  "댓글을 신고했어요.": "Comment reported.",
  신고됨: "Reported",
  신고하기: "Report",
  "첫 번째 댓글을 남겨보세요.": "Be the first to comment.",
  "님에게 답글 작성 중": " — replying",
  "답글 취소": "Cancel Reply",
  "로그인 후 댓글을 남길 수 있어요": "Sign in to leave a comment",
  "님에게 답글...": " — reply…",
  "댓글 입력": "Write a Comment",
  "댓글 등록": "Post Comment",
  "표시할 코스 정보가 없어요": "No Course Information Available",
  "저장한 코스의 장소 위치가 연결되면 이 지도에 자동으로 표시됩니다.":
    "Saved course locations appear on this map when available.",
  "지도 설정이 완료되면 저장한 코스가 여기에 표시됩니다.":
    "Saved courses will appear once maps are configured.",
  "코스, 장소": "Course, Place",
  "번 장소": " stop",
  "도보 경로 불러오는 중…": "Loading walking route…",
  "도보 경로를 불러오지 못했어요. 잠시 후 다시 확인해 주세요.":
    "Couldn't load the walking route. Please try again shortly.",
  "전체 저장 코스 보기": "View All Saved Courses",
  "저장 코스 ·": "Saved Course · ",
  "저장 피드 보기": "View Saved Post",
  "맛있는 하루 코스 ♥": "A Delicious Day ♥",
  소요: "Duration",
  장소: "Places",
  "맛있는 하루, 너무 완벽해! ♥": "A delicious day, just perfect! ♥",
  "추천 노출": "Recommendation Impressions",
  "상세·길찾기": "Details & Directions",
  "코스 열람": "Course Views",
  "코스 저장": "Course Saves",
  "피드 좋아요": "Post Likes",
  "중도 이탈": "Abandoned",
  월: "Mon",
  "서버 집계를 불러오지 못했습니다.": "Couldn't load server totals.",
  "D1 이벤트 집계를 불러오는 중…": "Loading D1 event totals…",
  "수집 이벤트": "Recorded Events",
  "활성 일수": "Active Days",
  "건 ·": " events · ",
  "아직 수집된 이벤트가 없습니다. 런치 모드에서 추천을 보고 결정을 완료하면 여기에 실제 데이터가 쌓입니다.":
    "No events recorded yet. Complete a recommendation flow in Lunchie to see activity here.",
  "D1 원본 이벤트 집계 · 마지막 조회": "D1 event totals · last updated ",
  비건: "Vegan",
  채식: "Vegetarian",
  글루텐프리: "Gluten-free",
  할랄: "Halal",
  "해산물 제외": "No Seafood",
  "오늘 뭐 먹지?": "What Shall We Eat?",
  "점심 메뉴 추천": "Lunch Recommendations",
  "취향과 상황에 딱 맞는": "Lunch suggestions to match ",
  "점심을 추천해드릴게요!": "your taste and occasion!",
  "먹지 않는 음식이 있나요?": "Any dietary preferences?",
  "나중에 바꿀 수 있어요": "You can change these later",
  "현재 위치는 점심 추천을 요청할 때만 사용하며, 가입 단계에서 저장하지 않아요.":
    "Your location is used only when requesting recommendations. It isn't saved during sign-up.",
  "추천 받기 시작하기": "Get Recommendations",
  "로그인 · 회원가입": "Sign In / Sign Up",
  "프로필을 불러오는 중…": "Loading profile…",
  "유저를 찾을 수 없어요": "User Not Found",
  "아직 실제 계정과 연결되지 않은 게시물일 수 있어요.":
    "This post may not be linked to an account yet.",
  "뒤로 가기": "Back",
  프로필: "Profile",
  "님의 피드": "'s Feed",
  "피드를 동기화하는 중…": "Syncing feed…",
  "아직 올린 피드가 없어요": "No Posts Yet",
  추가했어요: "Added",
  "식당 정보를 가져오지 못했어요": "Couldn't load restaurant details",
  "코스 제목을 입력해주세요": "Enter a course title",
  "식당을 1곳 이상 추가해주세요": "Add at least one restaurant",
  맛집: "Food Spots",
  "코스를 만들었어요! 🎉": "Course created! 🎉",
  "실제 식당 탐색": "Explore Restaurants",
  "식당 이름으로 검색 (Google)": "Search restaurants (Google)",
  "검색 중…": "Searching…",
  "검색에 실패했어요": "Search failed",
  "담은 식당": "Selected Restaurants",
  "평점 없음": "Not Rated",
  제거: "Remove",
  "코스 제목을 입력하세요": "Enter a course title",
  "코스 만들기": "Create Course",
  "이름을 입력해 주세요.": "Please enter your name.",
  "아이디는 영문 소문자, 숫자, 밑줄로 3~20자까지 입력해 주세요.":
    "Use 3–20 lowercase letters, numbers or underscores for your handle.",
  "프로필 업데이트 완료! ✅": "Profile updated! ✅",
  "이름을 저장하지 못했어요.": "Couldn't save your name.",
  "식단 설정을 저장하지 못했어요.": "Couldn't save dietary preferences.",
  "프로필 사진을 업데이트했어요! 📸": "Profile photo updated! 📸",
  "사진을 불러오지 못했어요": "Couldn't load the photo",
  "프로필 설정": "Profile Settings",
  "아바타 변경": "Change Avatar",
  "🏅 배지": "🏅 Badges",
  "오늘도 맛있는 하루를 위해": "Here's to another delicious day",
  "선택한 항목은 Quick Match에 자동 적용됩니다.":
    "Your preferences apply automatically to Quick Match.",
  "식단 요구 사항": "Dietary Requirements",
  "피하고 싶은 재료": "Ingredients to Avoid",
  계정: "Account",
  이름: "Name",
  아이디: "Handle",
  "영문 소문자, 숫자, 밑줄 · 3~20자":
    "Lowercase letters, numbers, underscores · 3–20 characters",
  "아바타 변경 닫기": "Close Avatar Editor",
  "사진 업로드": "Upload Photo",
  "사진을 지웠어요 — 이모지로 돌아가요": "Photo removed. Your emoji is back.",
  "사진 삭제하고 이모지로": "Remove Photo & Use Emoji",
  "기본 이모지": "Default Emoji",
  "로그인이 필요해요": "Sign In Required",
  팔로워: "Followers",
  팔로잉: "Following",
  목록: "List",
  "식단 설정": "Dietary Preferences",
  "로그인하면 식단 요구 사항과 피하고 싶은 재료를 저장할 수 있어요.":
    "Sign in to save dietary requirements and ingredients to avoid.",
  "프로필 확인 중…": "Checking profile…",
  "식당 상세 정보 (네이버 지도 스타일)": "Restaurant Details",
  "오늘의 런치픽": "Today's Lunchie Picks",
  "어제의 런치픽": "Yesterday's Lunchie Picks",
  "런치픽 저장 목록": "Saved Lunchie Picks",
  "런치픽 결과 보기": "View Lunchie Pick",
  런치픽: "Lunchie Picks",
  "런치픽 저장 취소": "Remove Saved Lunchie Pick",
  "저장을 취소하지 못했어요. 다시 시도해 주세요.":
    "Couldn't remove this saved item. Please try again.",
  "아직 저장한 런치픽이 없어요!": "No Saved Lunchie Picks Yet!",
  "해당 카테고리 런치픽이 없어요": "No Lunchie picks in this category",
  "아직 확정한 런치픽이 없어요!": "No Final Lunchie Picks Yet!",
  "Quick Match로 점심을 정하면 날짜별 여정으로 자동 기록돼요":
    "Quick Match choices are automatically added to your daily journey",
  "Quick Match 시작하기": "Start Quick Match",
  "저장 런치픽 보기 방식": "Saved Pick View",
  "저장 취소 확인 닫기": "Close Remove Confirmation",
  "저장을 취소할까요?": "Remove this saved pick?",
  "저장 목록에서 이 런치픽이 사라져요.":
    "This Lunchie pick will be removed from Saved.",
  취소: "Cancel",
  "저장 취소": "Remove from Saved",
  "유효하지 않은 초대 코드입니다.": "Invalid invite code.",
  "유효하지 않은 세션이거나 만료되었습니다.":
    "This session is invalid or has expired.",
  "닉네임을 입력해주세요!": "Please enter a nickname!",
  '" 세션에 참가했습니다! 🎉': '" joined! 🎉',
  "세션에 참가하지 못했어요. 초대 링크를 확인하고 다시 시도해 주세요.":
    "Couldn't join the session. Check the invite link and try again.",
  "초대 정보를 확인하는 중입니다...": "Checking your invitation…",
  "점심 세션 참여하기": "Join a Lunch Session",
  "친구들과 맛집 결정을 함께해요": "Choose a restaurant with your friends",
  초대장: "Invitation",
  "세션에 초대되었습니다!": "You're invited!",
  "내 캐릭터 선택": "Choose Your Character",
  "사용할 닉네임": "Your Nickname",
  "예: 맛잘알 길동이": "e.g. Foodie Alex",
  "식단 제약 사항": "Dietary Restrictions",
  "선택 사항": "Optional",
  "개 선택 ·": " selected · ",
  "선택한 식단 제약이 없어요": "No dietary restrictions selected",
  "메뉴 정보를 기준으로 필터링합니다. 심한 알레르기는 매장에 재료와 교차오염 여부를 꼭 확인해주세요.":
    "Filters use menu information. For severe allergies, confirm ingredients and cross-contamination risks with the restaurant.",
  "회원 로그인 완료": "Signed In",
  "저장된 취향을 기본값으로 적용했어요": "Your saved preferences are applied",
  로그아웃: "Sign Out",
  "로그인하면 저장된 취향을 불러올 수 있어요":
    "Sign in to load your saved preferences",
  로그인: "Sign In",
  "참가하는 중...": "Joining…",
  "세션 참여하기": "Join Session",
  "빠른 매칭이 취소됐어요.": "Quick Match was cancelled.",
  "더 이상 진행 중인 빠른 매칭이 아니에요.":
    "This Quick Match is no longer active.",
  "진행 중인 세션이 없어요": "No Active Session",
  "조건을 고르고 새 Lunchie 투표를 만들어 보세요.":
    "Choose your preferences and create a Lunchie vote.",
  "세션 만들기": "Create Session",
  "참여 완료!": "You're In!",
  "님이 시작하면": " starts the session, ",
  "바로 예선전으로 함께 이동해요.":
    "you'll join the preliminary round together.",
  "예선전으로 함께 이동하고 있어요.": "Joining the preliminary round together.",
  "명 참여 중": " participants",
  "시작 신호를 확인하고 있어요": "Waiting for the session to start",
  "혼자 고르기": "Choose Privately",
  "선택은 비밀": "Private Choices",
  "함께 공개": "Reveal Together",
  "동시에 확인": "Shared Results",
  "한 곳 결정": "Choose One Place",
  "의견 남기기": "Leave Feedback",
  "초대 링크를 복사했어요! 📋": "Invite link copied! 📋",
  "링크를 복사하지 못했어요. 브라우저 권한을 확인해 주세요.":
    "Couldn't copy the link. Check your browser permissions.",
  "공유 대신 초대 링크를 복사했어요.": "Invite link copied instead of sharing.",
  "초대 링크를 공유하지 못했어요. 잠시 후 다시 시도해 주세요.":
    "Couldn't share the invite link. Please try again shortly.",
  "현재 조건에 맞는 식당이 없어요. 반경이나 조건을 바꿔 주세요.":
    "No matching restaurants. Adjust your radius or preferences.",
  "투표를 시작하지 못했어요. 잠시 후 다시 시도해 주세요.":
    "Couldn't start voting. Please try again shortly.",
  "같이 고르고,": "Choose Together,",
  "한 번에 공개!": "Reveal Together!",
  "눈치 없이 선택": "Choose Freely",
  "득표는 비공개": "Private Vote Counts",
  "모두 동시에 공개": "Results for Everyone",
  "혼자 하는 Lunchie예요": "This Is a Solo Lunchie",
  "1명 정원으로 만든 세션은 초대할 수 없어요. 친구와 함께하려면 설정에서 ‘같이’를 선택해 새 세션을 만들어 주세요.":
    "Solo sessions don't support invitations. Choose Together in settings to create a group session.",
  "같이 하는 세션 만들기": "Create Group Session",
  "친구 초대하기": "Invite Friends",
  "참여용 QR 코드": " invite QR code",
  코드: "Code",
  "링크 복사": "Copy Link",
  공유하기: "Share",
  참여자: "Participants",
  "님의 프로필 사진": "'s profile photo",
  "님의 아바타": "'s avatar",
  나: "You",
  "세션 참여 완료": "Session Joined",
  "참여 완료": "Joined",
  "빈 자리": "Available seats: ",
  "개, 초대 링크 복사": "; copy invite link",
  "빈 자리에 친구 초대": "Invite a Friend",
  "자리 남음 · 탭해서 링크 복사": " seats left · tap to copy link",
  "정원이 모두 찼어요.": "This session is full.",
  "자리 더 초대할 수 있어요.": " more seats available.",
  "반경·조건 바꾸기": "Adjust Radius & Preferences",
  "투표를 여는 중…": "Starting vote…",
  "공유할 Munchie 피드를 찾을 수 없어요": "Munchie Post Not Found",
  "프로필에서 코스맵의 공유 버튼을 다시 눌러주세요.":
    "Try the course map's Share button from your profile again.",
  "공유 앱에서 Instagram 스토리를 선택해 주세요.":
    "Choose Instagram Stories in the share menu.",
  "9:16 스토리 이미지가 저장됐어요.": "9:16 story image saved.",
  "스토리 이미지를 공유하지 못했어요.": "Couldn't share the story image.",
  "9:16 스토리 이미지를 저장했어요.": "9:16 story image saved.",
  "이미지를 저장하지 못했어요.": "Couldn't save the image.",
  "Munchie 피드 링크를 복사했어요.": "Munchie post link copied.",
  "링크를 복사하지 못했어요.": "Couldn't copy the link.",
  "피드로 돌아가기": "Back to Feed",
  "스토리 공유하기": "Share Story",
  "공유할 화면 선택": "Choose a Share View",
  피드: "Feed",
  맵: "Map",
  앨범: "Album",
  "저장된 코스 위치가 없어요": "No Saved Course Locations",
  "원본 피드 고정 · 사진 변경 불가": "Original post · photos can't be changed",
  "작성한 사진 앨범과 배치를 그대로 9:16 스토리로 공유해요.":
    "Share your photo album and layout as a 9:16 story.",
  "어디에 공유할까요?": "Where Would You Like to Share?",
  "IG 스토리": "IG Story",
  "피드 링크": "Post Link",
  "스토리 만드는 중…": "Creating story…",
  "스토리 공유": "Share Story",
  "템플릿 목록으로 돌아가기": "Back to Templates",
  "이 템플릿을 나의 프로필에서 보관 처리할까요? 원본 코스와 피드는 그대로 유지돼요.":
    "Archive this template in your profile? The original course and post will remain.",
  "템플릿을 나의 프로필에서 보관 처리했어요":
    "Template archived in your profile",
  "저장을 해제했어요": "Removed from Saved",
  "코스를 저장했어요": "Course saved",
  "게시물 원본을 불러오는 중이에요…": "Loading original post…",
  "템플릿을 찾을 수 없어요": "Template Not Found",
  저장목록으로: "Saved",
  "템플릿 목록으로": "Templates",
  "템플릿 기본 양식 보기": "View Base Template",
  "템플릿 수정": "Edit Template",
  "템플릿 보관": "Archive Template",
  스팟: "Spots",
  "작성자의 한줄평": "Author's Review",
  "코스 저장 해제": "Unsave Course",
  "상세 코스 보기": "View Course Details",
  "밀어서 보기": "Swipe to View",
  슬라이드: "Slide",
  "빈 템플릿 보기": "View Empty Template",
  "사진 없는 기본 템플릿": "Base Template without Photos",
  "사진 없는 기본형": "Base Layout without Photos",
  "템플릿 한눈에 보기": "Browse Templates",
  "코스맵에 사용할 템플릿을 골라보세요.":
    "Choose a template for your course map.",
  "코스맵 템플릿": "Course Map Templates",
  "4:3 템플릿 · 전체": "4:3 Templates · All",
  "✏️ 스타일 커스텀": "✏️ Customize Style",
  "라인 색상": "Line Color",
  "라인 굵기": "Line Width",
  "라인 스타일": "Line Style",
  실선: "Solid",
  점선: "Dashed",
  그라데: "Gradient",
  장소명: "Place Names",
  "사진 스트립": "Photo Strip",
  "코스맵이 저장됐어요! 📸\n인스타 스토리에 스티커로 추가하세요!":
    "Course map saved! 📸\nAdd it as a sticker to your Instagram story!",
  "저장에 실패했습니다": "Couldn't save",
  "Lunchie Munchie 코스맵": "Lunchie Munchie Course Map",
  "링크가 복사됐어요! 📋": "Link copied! 📋",
  "Strava 스타일 투명 오버레이": "Strava-style Transparent Overlay",
  "📷 배경 사진을 추가하거나": "📷 Add a background photo or ",
  "투명 PNG로 내보내세요": "export a transparent PNG",
  "내보내기 형식": "Export Format",
  "투명 PNG": "Transparent PNG",
  "인스타 스티커용": "Instagram Sticker",
  "다크 배경": "Dark Background",
  "스토리 완성본": "Complete Story",
  "배경 사진": "Background Photo",
  "처리 중…": "Processing…",
  "저장 & 공유": "Save & Share",
  "📱 인스타 스토리에 올리는 법": "📱 Share to Instagram Stories",
  "로 저장 후 인스타 스토리 열기": ", then open Instagram Stories",
  "2. 내 사진을 스토리 배경으로 추가":
    "2. Add a photo as your story background",
  "3. 스티커 → 갤러리에서 코스맵 PNG 선택":
    "3. Stickers → choose the course map PNG from your gallery",
  "4. 크기·위치 조정 후 공유! 🎉":
    "4. Adjust the size and position, then share! 🎉",
  "카페 투어": "Cafe Tour",
  "성수동 카페를 하나씩 탐방해요": "Explore the cafes of Seongsu",
  "바 코스": "Bar Crawl",
  "이태원 바를 순서대로 즐겨요": "Explore Itaewon's bars",
  "맛 투어": "Food Tour",
  "다양한 음식을 코스로 즐겨요": "Enjoy a variety of food stops",
  "데이트 코스": "Date Course",
  "특별한 날을 위한 코스예요": "A course for a special day",
  "나만의 코스": "My Course",
  "직접 코스를 만들어보세요": "Create your own course",
  "핫플 코스": "Trending Spots",
  "지금 가장 핫한 장소들": "Explore today's popular places",
  "2시간": "2 hours",
  도보: "Walking",
  "1시간": "1 hour",
  "3시간": "3 hours",
  종일: "All Day",
  "예산 (1인당)": "Budget per Person",
  "이동 수단": "Travel Mode",
  대중교통: "Public Transport",
  차: "Driving",
  "근처 장소": "Nearby Places",
  "투어로 →": "Start Tour →",
  "투어 공유하기": "Share Tour",
  "투어 완료! 🎉": "Tour Complete! 🎉",
  "투어 완료!": "Tour Complete!",
  "투어 링크가 복사됐어요! 📋": "Tour link copied! 📋",
  "조건 선택으로 돌아가기": "Back to Preferences",
  "투어 공유": "Share Tour",
  "어떤 투어를": "What Kind of Tour ",
  "원하세요?": "Would You Like?",
  "카테고리를 선택하면 코스를 추천해드려요":
    "Choose a category for course recommendations",
  "조건 설정": "Preferences",
  "번 장소 검색 및 변경": " · search or change place",
  "번째 장소": " place",
  상세보기: "Details",
  선택: "Select",
  "순서 변경": "Reorder",
  "장소 삭제": "Remove Place",
  "코스 스팟": "Course Spots",
  "기록 사진": "Your Photos",
  "코스 링크를 복사했어요.": "Course link copied.",
  "코스 링크를 공유하지 못했어요.": "Couldn't share the course link.",
  "코스를 함께 둘러보세요.": "Explore this course together.",
  "저장을 해제했어요.": "Removed from Saved.",
  "코스를 저장했어요.": "Course saved.",
  "이미 코스에 담긴 장소예요.": "This place is already in your course.",
  "장소 정보를 가져오지 못했어요.": "Couldn't load place details.",
  "코스에는 장소가 최소 1곳 필요해요.": "A course needs at least one place.",
  "코스 순서와 장소를 저장했어요.": "Course order and places saved.",
  "코스맵과 먼치 피드를 삭제했어요.": "Course map and Munchie post deleted.",
  "새 장소 추가": "Add Place",
  "번 장소 변경": " · change place",
  "장소 검색 닫기": "Close Place Search",
  "지도검색 — 장소 이름 또는 주소": "Search places or addresses",
  "장소 검색 중…": "Searching places…",
  "온라인 장소 검색을 불러오지 못했어요.": "Couldn't load online place search.",
  "일치하는 장소가 없어요.": "No matching places.",
  "코스맵 보기": "View Course Map",
  "프로필 보기": "View Profile",
  "작성자 레벨 Lv.": "Author Level Lv.",
  "코스 공유하기": "Share Course",
  편집: "Edit",
  "지도 불러오는 중…": "Loading map…",
  "표시할 지도 좌표가 없어요.": "No map locations available.",
  선택됨: "Selected",
  삭제: "Delete",
  "좋아요 취소": "Unlike",
  "복사해서 편집": "Copy & Edit",
  "저장 해제": "Unsave",
  "코스맵 삭제 창 닫기": "Close Course Deletion",
  "게시물을 삭제하시겠습니까?": "Delete this post?",
  "코스맵과 먼치 피드 같이 삭제되며":
    "The course map and Munchie post will both be deleted. ",
  "다시 복구할 수 없습니다.": "This can't be undone.",
  확인: "Confirm",
  "이 코스로 만든 피드": "Posts from This Course",
  "같은 코스를 다녀온 사람들이 남긴 사진과 한줄평을 모았어요.":
    "Photos and reviews from people who visited this course.",
  "피드 정렬": "Sort Posts",
  최신순: "Newest",
  좋아요순: "Most Liked",
  "아직 이 코스의 피드가 없어요": "No Posts for This Course Yet",
  "첫 사진과 한줄평을 남겨보세요.": "Be the first to share a photo and review.",
  "피드 만들기": "Create Post",
  "코스맵을 정하세요": "Create Your Course Map",
  "템플릿을 선택하고 꾸며 보아요": "Choose a template and make it yours",
  미리보기: "Preview",
  "포스팅 완료!": "Posted!",
  "장소 정보를 불러오는 중…": "Loading place details…",
  "지도 위 장소 아이콘을 누르면": "Tap a place icon on the map to ",
  "번 장소로 선택돼요": " select this stop",
  "아래 숫자 마커를 먼저 눌러주세요": "Select a numbered marker first",
  "지도 또는 검색으로 장소를 고를 수 있어요 🗺️":
    "Choose places on the map or search 🗺️",
  "지도에 표시된 장소 아이콘을 누르거나": "Tap a place icon on the map or ",
  "아래 검색창에서 장소를 찾아보세요": "search for a place below",
  "이미 코스에 담긴 장소예요": "This place is already in your course",
  "먼저 아래 번호 마커를 눌러주세요": "Select a numbered marker below first",
  해시태그: "Hashtags",
  "+ 추가": "+ Add",
  "#태그": "#tag",
  한줄평: "Short Review",
  "한줄평 입력하기": "Write a Short Review",
  코스맵: "Course Map",
  "(최대": "(up to ",
  "곳)": " places)",
  "번 장소 검색": " · search place",
  "번호를 눌러 장소를 검색해보세요": "Select a number to search for a place",
  "지도검색 — 장소 이름": "Search place names",
  "Google 장소": "Google Places",
  "Google 장소 검색에 실패했어요": "Google place search failed",
  "Google 검색 결과가 없어요": "No Google search results",
  "저장된 식당": "Saved Restaurants",
  "두 글자 이상 입력하면 Google 장소도 검색해요":
    "Enter at least 2 characters to search Google Places",
  "Munchie 피드 사진은 최대": "Munchie posts support up to ",
  "장까지 사용할 수 있어요": " photos",
  "사진이 이미 목록에 있습니다, 목록에서 추가해주세요":
    "This photo is already in the list. Add it from there.",
  "템플릿에서 바로 편집": "Edit in Template",
  "사진 선택·이동": "Select & Move Photos",
  "사진 선택 및 이동": "Select and Move Photos",
  포토에디터: "Photo Editor",
  "편집할 사진을 먼저 선택해주세요": "Select a photo to edit",
  "포토에디터 열기": "Open Photo Editor",
  그리기: "Draw",
  "템플릿 전체에 그리기": "Draw on Template",
  하이라이터: "Highlighter",
  "템플릿 하이라이터": "Template Highlighter",
  지우개: "Eraser",
  "템플릿 지우개": "Template Eraser",
  "한 획 되돌리기": "Undo Stroke",
  "전체 그림 한 획 되돌리기": "Undo Last Template Stroke",
  "템플릿 펜 색상 선택": "Choose Template Pen Color",
  "펜 색상": "Pen Color",
  "템플릿 하이라이터 색상 선택": "Choose Template Highlighter Color",
  "하이라이터 색상": "Highlighter Color",
  "이전 템플릿": "Previous Template",
  "다음 템플릿": "Next Template",
  "템플릿 편집 캔버스": "Template Canvas",
  "아래 사진을 눌러 템플릿 위에 올린 뒤": "Choose a photo below, then ",
  "drag & drop으로 꾸며보세요": "drag and drop it onto your template",
  "템플릿 그림 지우기 영역": "Template Eraser Area",
  "템플릿 하이라이터 영역": "Template Highlighter Area",
  "템플릿 전체 그리기 영역": "Template Drawing Area",
  "사진 반시계 방향 회전": "Rotate Photo Counterclockwise",
  "사진 시계 방향 회전": "Rotate Photo Clockwise",
  "포토 에디터": "Photo Editor",
  "업로드한 사진목록 — 눌러서 템플릿에 올리기 (최대":
    "Uploaded photos — tap to add to template (up to ",
  "장)": " photos)",
  "사진 목록에서 삭제": "Remove Photo",
  "사진 식당 분류": "Photo Restaurant Category",
  "기타 사진": "Other Photos",
  "사진 GPS 기준": "Based on Photo GPS",
  "사진 추가": "Add Photos",
  "사진마다 식당을 확인해 선택하세요. JPEG 위치 정보가 식당 가까이 있으면 제안만 표시하며, 정확한 좌표는 저장하지 않아요.":
    "Choose the restaurant for each photo. JPEG locations near a restaurant are only suggestions; precise coordinates aren't stored.",
  원본: "Original",
  밝게: "Bright",
  빈티지: "Vintage",
  흑백: "Black & White",
  따뜻: "Warm",
  시원: "Cool",
  "사진을 저장하지 못했어요": "Couldn't save the photo",
  "사진 편집 뒤로가기": "Back from Photo Editor",
  뒤로가기: "Back",
  "사진 편집 초기화": "Reset Photo Edits",
  초기화: "Reset",
  "저장 중…": "Saving…",
  "텍스트 위치 이동": "Move Text",
  "템플릿에 표시되는 사진 영역": "Photo Area in Template",
  "크롭 영역 위쪽 크기 조절": "Resize Crop from Top",
  "크롭 영역 오른쪽 크기 조절": "Resize Crop from Right",
  "크롭 영역 아래쪽 크기 조절": "Resize Crop from Bottom",
  "크롭 영역 왼쪽 크기 조절": "Resize Crop from Left",
  "텍스트 입력": "Enter Text",
  추가: "Add",
  "사진 꾸미기": "Edit Photo",
  자르기: "Crop",
  텍스트: "Text",
  "펜 색상 선택": "Choose Pen Color",
  "하이라이터 색상 선택": "Choose Highlighter Color",
  필터효과: "Filters",
  "다음 →": "Next →",
  포스팅: "Post",
  "장소를 1곳 이상 찍어주세요": "Add at least one place",
  "한줄평을 입력해주세요": "Write a short review",
  "사진을 1장 이상 올려주세요": "Upload at least one photo",
  "장소와 사진을 확인한 뒤 다시 포스팅해주세요":
    "Check your places and photos, then try posting again",
  외: " and ",
  코스: "Course",
  "포스팅하려면 Google 로그인이 필요해요.": "Sign in with Google to post.",
  "포스팅에 실패했어요. 잠시 후 다시 시도해주세요":
    "Couldn't post. Please try again shortly.",
  "Munchie 코스맵 만들기": "Create Munchie Course Map",
  "이대로 포스팅할까요?": "Ready to Post?",
  "내 기록에 이렇게 저장돼요 · 미리보기에서는 버튼이 눌리지 않아요":
    "This is how your post will look · preview buttons are inactive",
  "나의 코스맵에 저장했어요": "Saved to My Course Maps",
  "+1 획득!": "+1 Earned!",
  "랜덤 음식 +1 획득!": "+1 Random Food Earned!",
  "프로필의 나의 런치박스에 바로 담았어요":
    "Added to your Lunchbox in your profile",
  보유: "Owned: ",
  "← 이전": "← Previous",
  "로그인 상태를 확인하지 못했어요.": "Couldn't verify your sign-in status.",
  "로그인 확인 중…": "Checking sign-in…",
  전체: "All",
  일: " days",
  "데이터 없음": "No data",
  "운영 대시보드": "Operations Dashboard",
  "Google 로그인 후 관리자 권한을 확인합니다.":
    "Sign in with Google to verify admin access.",
  "Google로 로그인": "Sign in with Google",
  "이 계정에는 운영 지표 접근 권한이 없습니다.":
    "This account does not have access to operational metrics.",
  "관리자는 Cloudflare Pages의":
    "Admins must add their Google emails to the Cloudflare Pages",
  "비밀 변수에 Google 이메일을 쉼표로 구분해 등록해야 합니다.":
    "secret as a comma-separated list.",
  노출: "Impressions",
  스와이프: "Swipes",
  결정: "Decisions",
  길찾기: "Directions",
  개요: "Overview",
  "카탈로그 현황": "Catalogue",
  "이미지 검수": "Photo Review",
  "이용·전환": "Usage & Conversion",
  "추천 정책": "Recommendation Policy",
  "데이터 계약": "Data Contract",
  "관리자 전용": "Admin Only",
  "개인 식별 정보와 정확한 위치는 집계 API·화면 어디에도 제공하지 않습니다.":
    "Personal identifiers and precise locations are excluded from aggregate APIs and screens.",
  "운영 및 학습 현황": "Operations & Learning",
  "개인 식별 정보 없이, 집계된 제품·추천·취향 신호만 표시합니다.":
    "Aggregated product, recommendation and preference signals, without personal identifiers.",
  새로고침: "Refresh",
  "집계 지표를 불러오는 중…": "Loading metrics…",
  "가입 이용자": "Registered Users",
  "기간 내 신규": "New in this period",
  명: " people",
  "활성 로그인 이용자": "Active Signed-in Users",
  "동안 행동 기록": " activity",
  "익명 체험 이용자": "Guest Users",
  "기기 쿠키 기준, 중복 제거": "Deduplicated by device cookie",
  "결정 완료": "Completed Decisions",
  "세션 결정률": "Session Completion Rate",
  "추천 수락률": "Recommendation Acceptance",
  "좋아요 ÷ 선호/비선호 스와이프": "Likes / preference votes",
  "학습 상태": "Learning Status",
  "학습 연결": "Learning Attribution",
  "건 · 결정": " events · decisions ",
  건: " events",
  "현재 데이터 현황": "Current Data",
  "식당 카탈로그와 연결된 사진·메뉴 데이터의 집계입니다.":
    "Restaurant catalogue and linked photo and menu totals.",
  "등록 식당": "Restaurants",
  곳: " restaurants",
  카테고리: "Categories",
  개: " items",
  "사진 연결": "Linked Photos",
  장: " photos",
  "곳 ·": " restaurants · ",
  "사진 메타데이터 색인": "Photo Metadata Index",
  미색인: "Not Indexed",
  "곳에서 색인": " restaurants indexed",
  "연결 사진": "Linked Photos",
  "장은 사용 가능": " photos available",
  "사용자 사진 분류": "User Photo Categories",
  "식당 연결": "Linked to Restaurants",
  "장 · 기타": " photos · other ",
  "구조화 메뉴": "Structured Menus",
  "곳 · 가격": " restaurants · prices ",
  "개 · 식단 근거": " items · dietary evidence ",
  "좌표 완성도": "Location Coverage",
  "곳 위치 보유": " restaurants with locations",
  "카탈로그 완성도": "Catalogue Completeness",
  "추천 가능한 식당 레코드에 필요한 핵심 필드의 충족률입니다.":
    "Coverage of the key fields required for restaurant recommendations.",
  주소: "Address",
  좌표: "Coordinates",
  설명: "Description",
  "식당 카테고리 구성": "Restaurant Categories",
  "현재 카탈로그의 업종·음식 분류 분포입니다.":
    "Cuisine and venue categories in the current catalogue.",
  "식당 수": "Restaurant Count",
  "등록된 카테고리 데이터가 없습니다.": "No category data available.",
  "지원 식단·제약": "Dietary Options",
  "식당 레코드에 명시된 식단 옵션입니다. 알레르기 안전성 보증이 아니라, 필터·추천에 사용할 수 있는 카탈로그 태그 현황입니다.":
    "Dietary tags listed in restaurant records for filtering and recommendations. These do not guarantee allergy safety.",
  "아직 식단 옵션 태그가 없습니다.": "No dietary tags yet.",
  "메뉴 구성 근거": "Menu Evidence",
  "구조화된 메뉴판 섹션에서 보수적으로 분류한 메뉴 항목 수입니다. 이 신호는 식당 분류를 덮어쓰지 않고, 추천 맥락 점수만 보강합니다.":
    "Menu item counts conservatively classified from structured menu sections. They supplement recommendation scores without changing restaurant categories.",
  식사: "Meals",
  카페: "Cafe",
  디저트: "Dessert",
  "메뉴 항목": "Menu Items",
  "음료·주류 전용, ‘SPECIAL’처럼 의미가 모호한 섹션은 근거로 집계하지 않습니다.":
    "Drinks-only, alcohol-only and ambiguous sections such as SPECIAL are excluded.",
  "카탈로그 예시": "Catalogue Samples",
  "리뷰 수와 평점을 기준으로 확인하는 대표 레코드입니다. 개인화 추천 순위가 아닙니다.":
    "Sample records by review count and rating, rather than personalized rankings.",
  식당: "Restaurant",
  분류: "Category",
  사진: "Photos",
  메뉴: "Menu",
  "표시할 식당 카탈로그가 없습니다.": "No restaurant catalogue available.",
  "이용 추이": "Usage Trends",
  "일별 고유 행위자·세션·최종 결정":
    "Daily unique users, sessions and final decisions",
  "활성 이용자": "Active Users",
  세션: "Sessions",
  "알고리즘 학습 준비도": "Learning Readiness",
  "자동 최적화의 성과가 아니라, 문서에 정의된 오프라인 평가를 시작해도 되는지의 전제 조건입니다.":
    "Prerequisites for starting the documented offline evaluation, rather than evidence of automatic optimization.",
  "다음:": "Next:",
  "불변 슬레이트": "Immutable Slates",
  "서버 노출": "Server Impressions",
  "예선 세션 선택": "Preliminary Votes",
  "기존 세션 선택 중": "Of the previous session votes, ",
  "건은 추천 슬레이트와 연결되지 않아 학습 표본에서 제외됐습니다. 새 선택부터 서버가 자동 연결합니다.":
    " were excluded from learning samples because they lacked slate attribution. New votes are attributed automatically.",
  "Lunchie 퍼널": "Lunchie Funnel",
  "추천 노출부터 길찾기까지의 행동 전환":
    "Conversion from recommendations to directions",
  건수: "Count",
  재추천: "New Recommendations",
  "Propensity 기록": "Propensity Coverage",
  "Score 기록": "Score Coverage",
  "계측 계약": "Instrumentation Contract",
  "추천을 받은 뒤의 클라이언트 값이 아니라, 서버가 저장한 노출 증거를 기준으로 합니다.":
    "Based on server-recorded impression evidence.",
  "포함 확률 (propensity)": "Inclusion Probability (Propensity)",
  "정책 점수": "Policy Score",
  "정책 버전": "Policy Version",
  "요청 맥락 스냅샷": "Request Context Snapshot",
  "추천 정책 학습 신호": "Recommendation Learning Signals",
  "정책 버전별 노출·스와이프·수락률입니다. 표본이 작을 때는 의사결정에 사용하지 마세요.":
    "Impressions, swipes and acceptance by policy version. Small samples should not guide decisions.",
  수락: "Accepted",
  좋아요: "Likes",
  "아직 모델 버전이 기록된 추천 데이터가 없습니다.":
    "No versioned recommendation data yet.",
  "현재 정책의 점수 구성": "Current Policy Score Breakdown",
  "서버가 실제로 낸 슬레이트": "Server-issued slates: ",
  "개 항목의 평균 점수 기여입니다. ‘왜 추천됐는지’의 정책 설명이며, 사용자의 결정 원인이나 인과 효과는 아닙니다.":
    " items with average score contributions. These explain policy scoring, not the causes of user decisions.",
  "평균 점수 기여": "Average Score Contribution",
  기여도: "Contribution",
  "새 추천 슬레이트가 쌓이면 점수 구성부터 표시합니다.":
    "Score breakdowns will appear as new recommendation slates are recorded.",
  "카테고리별 결정 반응": "Response by Category",
  "노출 후 LIKE/NOPE 반응의 관측 차이입니다. 카테고리는 무작위 배정되지 않으므로 ‘결정에 미친 인과 영향’이 아니라 다음 정책 가설을 위한 신호입니다.":
    "Observed LIKE/NOPE responses after exposure. Categories are not randomized, so these inform policy hypotheses rather than causal conclusions.",
  반응: "Response",
  "전체 대비": "vs. Overall",
  "· 노출": "· impressions ",
  "카테고리별 추천 증거가 아직 없습니다.":
    "No category-level recommendation evidence yet.",
  "관찰된 취향 분포": "Observed Preferences",
  "기간 내 최종 선택 카테고리를 익명·집계해 표시합니다. 개인 페르소나는 노출하지 않습니다.":
    "Anonymous totals of final-choice categories for this period. Individual personas are not shown.",
  "회 ·": " times · ",
  "아직 최종 결정 데이터가 없습니다.": "No final decisions yet.",
  "개인 식별자·정확 위치·개별 취향 벡터는 이 화면과 API에 포함되지 않습니다. 마지막 집계":
    "Personal identifiers, precise locations and individual preference vectors are excluded. Last updated: ",
  "운영 지표를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.":
    "Couldn't load operational metrics. Please try again shortly.",
  "로그인을 확인하고 있어요": "Checking sign-in",
  "잠시만 기다려 주세요.": "Please wait a moment.",
  "로그인을 완료하지 못했어요": "Couldn't complete sign-in",
  "Google 로그인을 다시 시작해 주세요.":
    "Please try signing in with Google again.",
  "로그인 페이지로 돌아가기": "Back to Sign In",
  "프로필로 돌아가기": "Back to Profile",
  "로컬 Google 로그인 설정이 없어요. 프로젝트 루트의 .dev.vars에 Google OAuth 설정을 복구한 뒤 개발 서버를 다시 시작해 주세요.":
    "Local Google sign-in settings are missing. Restore Google OAuth settings in .dev.vars and restart the development server.",
  "Google 계정 정보를 읽지 못했어요. 계정에 이름이나 프로필 사진이 없어도 로그인은 가능해야 하므로, 다시 시도해도 반복되면 이 오류 코드를 알려주세요.":
    "Couldn't read your Google account. Sign-in should work without a name or photo. If this persists, report the error code.",
  "Google 인증 코드를 앱 세션으로 바꾸지 못했어요.":
    "Couldn't exchange the Google authorization code for an app session.",
  "Google 로그인 상태 확인이 만료됐어요.":
    "Your Google sign-in request expired.",
  "오류 코드:": "Error code:",
  "Google 로그인 다시 시도": "Try Google Sign-in Again",
  "코스를 찾을 수 없어요": "Course not found",
  "코스 탐색": "Explore Courses",
  "저장 취소됨": "Removed from Saved",
  "코스를 저장했어요! 🔖": "Course saved! 🔖",
  "이전 화면으로 돌아가기": "Back",
  "코스 상세": "Course Details",
  시간: " hours",
  "개 장소": " places",
  "코스 순서": "Course Order",
  저장됨: "Saved",
  저장하기: "Save",
  "코스 따라가기": "Follow Course",
  "코스 탐색 🗺️": "Explore Courses 🗺️",
  "코스가 없어요": "No courses yet",
  "다른 필터를 선택해보세요": "Try a different filter",
  "코스 상세로 돌아가기": "Back to Course",
  "코스맵 공유": "Share Course Map",
  "다음 장소": "Next Place",
  "지금 위치에서 약": "About ",
  이전: "Previous",
  "다음 장소로": "Next Place",
  "코스맵 공유 🗺️": "Share Course Map 🗺️",
  "코스를 탐색해보아요": "Explore courses",
  "새 코스 만들기": "Create Course",
  "퀵매치로 돌아가기": "Back to Quick Match",
  "저장목록으로 돌아가기": "Back to Saved",
  "피드를 불러오는 중이에요…": "Loading feed…",
  "피드를 찾을 수 없어요": "Post not found",
  돌아가기: "Back",
  "수정할 수 없는 피드예요.": "You can't edit this post.",
  프로필로: "Profile",
  "서버에서 수정 권한을 확인하지 못했어요.":
    "Couldn't verify editing permissions.",
  "Munchie 피드를 수정했어요.": "Munchie post updated.",
  뒤로: "Back",
  "Munchie 피드 수정": "Edit Munchie Post",
  "연결된 코스맵": "Linked Course Map",
  "기존에 게시한 피드에서 시작해 사진·템플릿·그림을 모두 다시 꾸밀 수 있어요. 연결된 코스는 그대로 유지돼요.":
    "Edit the photos, template and drawings in your published post. The linked course stays the same.",
  "한줄평을 입력하세요": "Write a short review",
  "수정 완료": "Save Changes",
  "사진을 꾸몄어요 ✨": "Photo updated ✨",
  옷장: "Wardrobe",
  "방 꾸미기": "Decorate Room",
  맛도감: "Food Collection",
  성장일지: "Growth Journal",
  "나만의 런치메이트 공간": "Your Lunchmate Space",
  "준비 중": "Coming Soon",
  "런치메이트 미리보기": "Lunchmate Preview",
  맛추억: "Food Memories",
  "런치메이트 룸에서 움직이는 런치메이트": "Lunchmate moving in the room",
  "레이어 조합을 확인하는 미리보기예요": "A preview of your selected layers",
  "직접 들어온 화면이라 맛추억은 초기 미리보기 상태로 표시돼요.":
    "Food memories are shown in their initial preview state.",
  "런치메이트 룸 기능": "Lunchmate Room Features",
  "런치메이트 룸 메뉴": "Lunchmate Room Menu",
  "선택한 방 구성은 프로필과 런치메이트룸에 바로 적용돼요.":
    "Room changes appear immediately in your profile and Lunchmate room.",
  "런치메이트에게 나눈 음식 기록이 여기에 모일 예정이에요.":
    "Food you've shared with your Lunchmate will appear here.",
  "음식 8종 준비 중": "8 Foods Coming Soon",
  "음식 8종을 준비하고 있어요": "Preparing 8 food options",
  "레벨과 칭호 기록을 준비하고 있어요.":
    "Your level and title history is coming soon.",
  "현재 Preview Level": "Current Preview Level",
  "맛추억 미리보기 진행도": "Food memory preview progress",
  "다음 Level까지": "Until the next level",
  "레벨별 성장 보상": "Level Rewards",
  "다음 레벨 보상": "Next Level Reward",
  "새로운 꾸미기 아이템": "New Customization Items",
  "레벨이 오르면 옷장 아이템을 받을 수 있어요.":
    "Earn wardrobe items as you level up.",
  커피: "Coffee",
  밥: "Meals",
  "내 코스튬을 입고 눈을 깜빡이는 런치메이트":
    "Lunchmate blinking in your outfit",
  카드: "Card",
  "(선택됨)": "(Selected)",
  음식: "Food",
  "오늘의 여정": "Today's Journey",
  "에서의 기록이 추가됐어요.": " added to your journey.",
  "이(가) 다음 여정으로 등록됐어요.": " added as your next stop.",
  "새 좋아요": "New Like",
  "내 Munchie 피드에 좋아요": "Your Munchie post received ",
  "개가 달렸어요.": " reactions.",
  "새 싫어요": "New Dislike",
  "내 Munchie 피드에 싫어요": "Your Munchie post received ",
  "님의 새 코멘트": " left a new comment",
  "알림 열기": "Open Notifications",
  "런치로 같이 메뉴 정하기!": "Choose a meal together with Lunchie!",
  "먼치로 함께 맛집 코스 탐방!": "Explore food courses together with Munchie!",
  "런치로 같이 점심 정하기!": "Choose lunch together with Lunchie!",
  "먼치로 함께 맛집 코스 탐방": "Explore food courses together with Munchie",
  더보기: "See More",
  "알림 닫기": "Close Notifications",
  알림: "Notifications",
  닫기: "Close",
  "오늘 등록된 여정이 아직 없어요.": "No journey stops added today.",
  "모두 읽음": "Mark All Read",
  "더이상 새로운 알람이 없어요": "You're all caught up",
  "식당 위치를 불러오는 중…": "Loading restaurant location…",
  "식당 정보를 찾을 수 없습니다.": "Restaurant not found.",
  "저장 목록으로": "Saved",
  "Lunchie 런치픽으로 돌아가기": "Back to Lunchie Pick",
  "지도를 불러올 수 없어요": "Couldn't load the map",
  "Google 지도 설정을 확인해 주세요.":
    "Please check your Google Maps settings.",
  "메뉴 (": "Menu (",
  "메뉴 사진": "Menu Photos",
  "저장 목록으로 돌아가기": "Back to Saved",
  "저장한 런치픽을 찾을 수 없어요.": "Saved Lunchie pick not found.",
  랜덤: "Surprise Me",
  "검증된 인기 메뉴": "Popular Favorites",
  "분위기 좋은 곳": "Great Atmosphere",
  "혼자서도 편하게": "Solo Friendly",
  "커피와 여유": "Coffee Break",
  "퇴근 후 한잔": "After-work Drinks",
  "느긋한 한 끼": "A Relaxed Meal",
  "달콤한 마무리": "Something Sweet",
  "가격까지 만족": "Great Value",
  "이 브라우저에서는 위치 정보를 사용할 수 없습니다.":
    "Location is unavailable in this browser.",
  "위치 권한이 꺼져 있어요. 주소창의 사이트 설정에서 위치를 허용한 뒤 다시 시도해 주세요.":
    "Location permission is off. Enable it in your browser's site settings and try again.",
  "현재 위치를 확인하지 못했습니다. 잠시 후 다시 시도해 주세요.":
    "Couldn't find your location. Please try again shortly.",
  "마감 시간": "Time Limit",
  분: " min",
  "인원 수": "Group Size",
  혼자: "Solo",
  "빠른 인원 선택": "Quick Group Size",
  "혼자 빠른 선택": "Choose Solo",
  "명 빠른 선택": " people",
  거리: "Distance",
  "검색 거리": "Search Radius",
  "현재 위치를": "Your location is ",
  "(으)로 확인했어요.": ".",
  "현재 위치를 확인하지 못했습니다.": "Couldn't find your location.",
  호스트: "Host",
  "의 점심 세션": "'s Lunch Session",
  "빠른 매칭을 시작합니다.": "Starting Quick Match.",
  "세션이 만들어졌어요. 친구를 초대해 보세요.":
    "Session created. Invite your friends!",
  "진행 중인 대기방으로 이동합니다.": "Returning to your active lobby.",
  "진행 중인 투표로 이동합니다.": "Returning to your active vote.",
  "진행 중인 빠른 매칭을 확인하지 못했어요. 다시 시도해 주세요.":
    "Couldn't check your active Quick Match. Please try again.",
  "세션을 만들지 못했어요. 잠시 후 다시 시도해 주세요.":
    "Couldn't create a session. Please try again shortly.",
  "새 Quick Match를 시작하지 못했어요.": "Couldn't start a new Quick Match.",
  "기존 세션은 종료됐지만 새 세션을 만들지 못했어요. 다시 시도해 주세요.":
    "Your previous session ended, but a new one couldn't be created. Please try again.",
  "오늘 먹고 싶은 메뉴를 골라보세요": "What are you craving today?",
  "진행 중인 빠른 매칭을 확인하지 못했어요":
    "Couldn't check your active Quick Match",
  "저장된 세션은 유지하고 있어요. 새 세션을 만들기 전에 다시 확인해 주세요.":
    "Your saved session is still available. Check it again before creating a new session.",
  "다시 시도": "Try Again",
  "저장된 세션 지우기": "Clear Saved Session",
  "진행 중인 빠른 매칭": "Active Quick Match",
  "대기 중": "Waiting",
  "최종 선택 중": "Final Choice",
  "투표 중": "Voting",
  "서버에서 확인된 세션으로 바로 이어서 할 수 있어요.":
    "Continue your active session.",
  "🙋 혼자": "🙋 Solo",
  "🤝 함께": "🤝 Together",
  "대기방으로 돌아가기": "Back to Lobby",
  "빠른 매칭 계속하기": "Continue Quick Match",
  "오늘의 빠른 매칭": "Today's Quick Match",
  "어떤 분위기인가요?": "What's the occasion?",
  "선택하지 않음": "No Preference",
  "반경 제한 없음": "No Radius Limit",
  "확인 중…": "Checking…",
  "위치 다시 확인": "Refresh Location",
  "현재 위치 확인": "Find My Location",
  "현재 위치 ·": "Current location · ",
  이내: " radius",
  "· 반경 제한 없음": "· No radius limit",
  "선택한 반경을 적용하려면 현재 위치 권한이 필요해요.":
    "Enable location to use your selected radius.",
  "위치 권한 없이 전체 후보에서 추천받을 수 있어요.":
    "Get recommendations without location permission.",
  인원: "People",
  최대: "Up to ",
  "명까지 함께 선택할 수 있어요.": " people can choose together.",
  마감: "Deadline",
  "진행 중인 세션 확인 중…": "Checking active session…",
  "준비하는 중…": "Preparing…",
  "기존 세션 종료 후": "After ending your current session, ",
  혼자로: "solo",
  명으로: " people",
  시작하기: "Start",
  "투표 계속하기": "Continue Voting",
  "퀵매치 시작!": "Start Quick Match!",
  "세션 만들고 초대하기": "Create Session & Invite",
  "새 인원 설정으로 시작할까요?": "Start with a new group size?",
  현재: "Current: ",
  "명 세션이 진행 중이에요.": " people in an active session.",
  "설정을 적용하려면": "To apply these settings, ",
  "기존 세션을 종료하고": "end your current session and ",
  "기존 세션에서 나간 뒤": "leave your current session and ",
  "새 Quick Match를 만들어야 해요.": "create a new Quick Match.",
  "기존 세션 계속하기": "Continue Current Session",
  "새 세션 준비 중…": "Preparing new session…",
  종료: "End",
  나가기: "Leave",
  "후 새로 시작": " & Start Again",
  "음식 종류": "Cuisine",
  "추천 투표": "Recommendation Vote",
  만족도: "Satisfaction",
  게임: "Game ",
  "단계:": "stage: ",
  "라운드 통계 결과": " round results",
  "모두의 선택을 기다리는 중": "Waiting for Everyone",
  "개별 답은 숨긴 채 완료 인원만 표시해요. 모두 끝나면 통계를 동시에 공개합니다.":
    "Individual choices stay private. Results appear together when everyone finishes.",
  "명 선택 완료": " people finished",
  "🔒 이름과 개별 선택은 공개하지 않아요":
    "🔒 Names and individual choices stay private",
  "익명 집계 ·": "Anonymous results · ",
  총: "Total: ",
  "명 기준": " participants",
  "오늘의 입맛 분포": "Today's Cravings",
  "모두의 음식 종류 선택을 익명으로 합쳤어요.":
    "Everyone's cuisine choices, combined anonymously.",
  "추천 투표 시작 →": "Start Recommendation Vote →",
  "오늘 어떤 음식이 끌려요?": "What are you craving?",
  "끌리는 종류를 모두 고른 뒤 선택을 확정해요.":
    "Choose all the cuisines you like, then confirm.",
  "음식 종류 복수 선택": "Choose Cuisines",
  "선택 저장 중…": "Saving choices…",
  "개 선택 완료 →": " selected →",
  "여러 종류를 고를 수 있고, 확정 후 통계를 보여드려요.":
    "Choose multiple cuisines. Results appear after confirmation.",
  다른: "Other ",
  "명의 답은 보이지 않고 완료 인원만 보여요.":
    " participants' choices stay private. Only completion totals are shown.",
  "결승 후보를 준비하고 있어요": "Preparing Finalists",
  "빠른 매칭과 식당 후보를 준비하고 있어요…":
    "Preparing Quick Match and restaurant options…",
  "빠른 매칭을 불러오지 못했어요": "Couldn't Load Quick Match",
  "인터넷 연결을 확인하고 다시 시도해 주세요.":
    "Check your connection and try again.",
  "아직 추천할 식당이 없어요": "No Restaurants Available Yet",
  "이 빠른 매칭에 맞는 식당 후보를 불러오지 못했어요.":
    "Couldn't load restaurants for this Quick Match.",
  "조건에 맞는 식당이 없어요": "No Matching Restaurants",
  "검색 거리를 늘리거나 취향 조건을 조정해 보세요.":
    "Try a wider radius or adjust your preferences.",
  "빠른 매칭을 다시 준비할게요": "Let's Start a New Quick Match",
  "진행 중인 빠른 매칭이 없어요. 설정에서 새로 시작해 주세요.":
    "No active Quick Match. Start a new one from settings.",
  "더 이상 참여할 수 없는 빠른 매칭이에요": "This Quick Match Is Unavailable",
  "이미 종료·만료·취소됐거나 대기방에서 나간 세션일 수 있어요.":
    "The session may have ended, expired or been cancelled, or you may have left it.",
  "아직 빠른 매칭이 시작되지 않았어요": "Quick Match Hasn't Started",
  "대기방으로 돌아가 호스트가 시작할 때까지 기다려 주세요.":
    "Return to the lobby and wait for the host to start.",
  "조건 수정하기": "Adjust Preferences",
  "설정으로 돌아가기": "Back to Settings",
  "이 세션 관리": "Manage Session",
  "등록된 음식 사진이 없어요": "No Food Photos Available",
  "메뉴 사진 전체": "All Menu Photos",
  "장 중": " photos · ",
  번째: "",
  "개 중": " options · ",
  "번째 음식점": " restaurant",
  "탭 → 메뉴 보기": "Tap → View Menu",
  "상세정보 보기": "View Details",
  "상세보기 ›": "Details ›",
  "좋아요 ♡": "Like ♡",
  "패스 ✕": "Pass ✕",
  "· 메뉴 둘러보기": "· Browse Menu",
  "메뉴 닫기": "Close Menu",
  "식당 상세보기": "Restaurant Details",
  "이전 사진": "Previous Photo",
  "다음 사진": "Next Photo",
  "주소가 복사됐어요! 📋": "Address copied! 📋",
  "이미지가 저장됐어요! 🎉": "Image saved! 🎉",
  "이미지 저장에 실패했어요": "Couldn't save the image",
  "오늘의 점심은": "Today's lunch is ",
  "이미지가 저장됐어요. 갤러리에서 공유해보세요! 📤":
    "Image saved. Share it from your gallery! 📤",
  "공유에 실패했어요": "Couldn't share",
  "만족도를 남겼어요!": "Feedback submitted!",
  "만족도를 저장하지 못했어요. 다시 시도해 주세요.":
    "Couldn't save your feedback. Please try again.",
  "식사 후 별점을 남겼어요!": "Meal rating submitted!",
  "별점을 저장하지 못했어요. 다시 시도해 주세요.":
    "Couldn't save your rating. Please try again.",
  "오늘의 점심 당첨!": "Today's Lunch Pick!",
  "예약 기능은 준비 중이에요.": "Reservations are coming soon.",
  예약하기: "Reserve",
  "런치픽에 추가했어요.": "Added to your Lunchie picks.",
  "런치픽을 저장하지 못했어요. 다시 시도해 주세요.":
    "Couldn't save your Lunchie pick. Please try again.",
  "런치픽 저장됨": "Lunchie Pick Saved",
  "런치픽에 추가": "Save Lunchie Pick",
  "다시 고르기": "Choose Again",
  "이 결정에 얼마나 만족해요?": "How happy are you with this choice?",
  "다른 사람에게는 점수가 보이지 않아요.": "Your score stays private.",
  아쉬워요: "Not Quite",
  "완전 만족": "Love It",
  "결과 만족도": "Choice Satisfaction",
  "만족도 제출 완료 ✓": "Feedback Submitted ✓",
  "집계 중…": "Calculating…",
  "만족도 보내기": "Submit Feedback",
  "다음 모임 추천에 반영할게요.":
    "Your feedback helps with future recommendations.",
  "4라운드 통계 결과": "Round 4 Results",
  "전체 만족도 평균": "Average Satisfaction",
  아쉬움: "Disappointed",
  괜찮음: "Okay",
  만족: "Happy",
  "익명 응답": "Anonymous responses",
  "다녀오셨나요?": "Have you visited?",
  "결정 만족도와 별개로, 실제 식사 경험을 별점으로 남겨주세요.":
    "Rate your actual meal separately from your satisfaction with the choice.",
  "식사 후 별점 선택": "Rate Your Meal",
  점: " points",
  "점 · 실제 방문 완료": " stars · visited",
  "별을 눌러 방문 후 만족도를 선택하세요":
    "Choose a star rating after your visit",
  "식사 후 별점 제출 완료 ✓": "Meal Rating Submitted ✓",
  "별점 집계 중…": "Calculating ratings…",
  "다녀왔어요 · 별점 보내기": "I've Visited · Submit Rating",
  "식사 후 만족도 통계": "Meal Rating Results",
  "명이 다녀왔어요": " people visited",
  "식사 후 평균": "Average meal rating",
  "개별 별점은 숨기고 익명 통계만 보여줘요.":
    "Individual ratings stay private. Only anonymous totals are shown.",
  "🌱 다 드시고 나서 —": "🌱 After your meal — ",
  "커피·디저트": "Coffee & Dessert",
  "도 근처에 있어요.": " are nearby too.",
  퀵매치: "Quick Match",
  "에서 커피·디저트를 선택해 다시 찾아보세요.":
    ": choose coffee or dessert to explore again.",
  "공유 카드 만들기": "Create Share Card",
  "주소 복사": "Copy Address",
  퀵매치로: "Quick Match",
  저장: "Save",
  "이미지 공유하기": "Share Image",
  "마지막 도전자! 🏆": "Last Contender! 🏆",
  "여기 어때요? 🤔": "How About This Place? 🤔",
  "좋아요 중 마지막 후보예요 · 별로면 새로 추천받아요":
    "Your last liked option · get new recommendations if it isn't right",
  "🏆 유일한 후보": "🏆 Only Contender",
  "최종 선택 저장 중…": "Saving final choice…",
  "이곳으로 결정!": "Choose This Restaurant!",
  "별로예요 · 새로 추천받기": "Not for Me · Get New Options",
  "나만의 결승전 🏆": "My Final Showdown 🏆",
  "결승전 🏆": "Final Showdown 🏆",
  "내가 고른 TOP 2 · 최종 우승자를 선택해요": "My Top 2 · choose the winner",
  "친구들과 함께 고른 TOP 2 · 마음에 드는 한 곳을 선택해요":
    "Our Top 2 · choose your favorite",
  "✓ 선택됨": "✓ Selected",
  대결: "Showdown",
  "음식점을 선택해주세요": "Choose a Restaurant",
  "둘 다 별로!": "Neither Works!",
  "최종 선택을 저장하지 못했어요. 다시 시도해 주세요.":
    "Couldn't save your final choice. Please try again.",
  "합의가 어려웠어요": "We Couldn't Agree",
  "여러 번 골라봤지만 모두 마음에 드는 곳을 못 찾았어요.":
    "We tried several options but couldn't find a place everyone liked.",
  "다른 동네로 넓히거나 나중에 다시 시도해볼까요?":
    "Try another neighborhood or come back later.",
  처음으로: "Home",
  "두 번 다 아쉬웠네요": "Neither Round Worked Out",
  "한 번 더 시도하면 마지막 기회예요.":
    "One more round will be the last attempt.",
  "여기서 처음부터 다시 시작할 수도 있어요.":
    "You can also start again from scratch.",
  "마지막으로 한 번 더 →": "One Last Try →",
  "처음부터 다시 시작": "Start Over",
  "다른 곳으로 다시 골라요": "Let's Try Other Places",
  "‘둘 다 별로’가 많았어요.": "Most people chose neither option.",
  "방금 후보는 빼고 새로운 곳을 가져왔어요.":
    "We've brought new places, excluding the previous options.",
  "다시 고르기 시작 →": "Choose Again →",
  "그룹 추천 투표 결과": "Group Recommendation Results",
  "개별 답은 숨기고 전체 응답 수만 공개했어요.":
    "Individual choices stay private. Only total responses are shown.",
  추천: "Recommend",
  비추천: "Not Recommended",
  "그저 그래요": "Neutral",
  "TOP 2 대결 보기 →": "View Top 2 →",
  "최종 통계 보기 →": "View Final Results →",
  "개 평가": " ratings",
  "결정됐어요!": "It's Decided!",
  "모든 친구들이 투표를 완료했습니다": "Everyone has finished voting",
  "3라운드 통계 결과": "Round 3 Results",
  "TOP 2 최종 득표": "Top 2 Final Votes",
  "표 ·": " votes · ",
  "둘 다 별로": "Neither",
  표: " votes",
  "익명 집계 · 개인 선택은 비공개":
    "Anonymous totals · individual choices stay private",
  "결과 확인하기 🎉": "See Results 🎉",
  "내 선택을 잠갔어요!": "Your Choice Is Locked!",
  "다른 사람의 답은 아직 비밀 · 모두 끝나면":
    "Everyone else's choices stay private. Once everyone finishes, ",
  "최종 결과가": "the final results ",
  "결승 후보가": "the finalists ",
  "같이 열려요.": "will appear together.",
  "공정한 선택 방식": "Fair Choices",
  "독립 선택": "Independent Choices",
  "동시 공개": "Shared Reveal",
  "의견 존중": "Everyone Counts",
  "투표 완료": "Vote Complete",
  "선택 완료": "Choice Complete",
  "결승 투표 현황": "Final Vote Progress",
  "예선 투표 현황": "Preliminary Vote Progress",
  투표: "Vote",
  완료: "Complete",
  "남은 시간": "Time Left",
  "연결을 다시 확인하고 있어요. 완료 신호는 자동으로 재전송됩니다.":
    "Reconnecting. Your completion signal will retry automatically.",
  "🔒 선택 내용은 끝까지 비공개": "🔒 Individual choices stay private",
  "누가 무엇을 골랐는지, 몇 장을 골랐는지는 보여주지 않아요.":
    "We don't reveal who chose what or how many cards they selected.",
  "기다리지 않고 지금 진행 · 호스트": "Continue Now · Host",
  "음식 종류 선택을 저장하지 못했어요. 다시 시도해 주세요.":
    "Couldn't save your cuisine choices. Please try again.",
  "선택을 저장하지 못했어요. 다시 눌러 주세요.":
    "Couldn't save your choice. Please try again.",
  "추천 투표 결과": "Recommendation Vote Results",
  "한 곳씩 평가한 결과를 합쳤어요. 이제 TOP 2가 맞붙습니다.":
    "Your restaurant ratings are combined. Your Top 2 are next.",
  "계속 별로였네요": "These Options Didn't Work Out",
  "마음에 드는 곳을 못 찾았어요": "No Favorite Found",
  "여러 번 골라봤지만 계속 별로였어요.":
    "We tried several rounds, but none felt right.",
  "TOP 2 최종 결과": "Top 2 Final Results",
  "최종 선택이 집계됐어요. 우승 식당을 공개합니다.":
    "Final choices are counted. Here's the winning restaurant.",
  "우승 식당과 만족도 보기 →": "View Winner & Feedback →",
  "최종 1표": "1 final vote",
  "빠른 매칭 설정으로 돌아가기": "Back to Quick Match Settings",
  "ROUND 2 · 추천 투표": "ROUND 2 · RECOMMENDATION VOTE",
  "이 식당을 추천할까요?": "Would you recommend this restaurant?",
  "한 곳씩 보고 평가해요 ·": "Rate each restaurant · ",
  "현재 위치에서 가장 가까운 후보": "Closest to Your Location",
  "선택한 모든 식단 조건을 매장에서 보장하지는 않아요. 제외 재료는 반영했지만 주문 전에 매장에 다시 확인해 주세요.":
    "Restaurants may not meet every dietary preference. Ingredient exclusions were applied, but please confirm with the restaurant before ordering.",
  "Quick Match 음식점 후보를 준비하고 있어요":
    "Preparing Quick Match Restaurants",
  "추천 투표를 준비 중!": "Getting the Vote Ready!",
  "다른 사람의 선택은 보이지 않아요 · 내 답에만 집중해요":
    "Other choices stay private · choose what feels right to you",
  비추천해요: "Not for Me",
  추천해요: "Recommend",
  "맛있는 한입 고마워! 😋": "Thanks for the tasty bite! 😋",
  "주소 정보 준비 중": "Address coming soon",
  "주소 정보 없음": "Address unavailable",
  "영업시간 정보 없음": "Opening hours unavailable",
  "게시물을 삭제하지 못했어요.": "Couldn't delete this post.",
  "세션을 서버에 저장하지 못했어요.": "Couldn't save the session.",
  "세션에 참가하지 못했어요.": "Couldn't join the session.",
  "준비 상태를 바꾸지 못했어요.": "Couldn't update your ready status.",
  "세션을 시작하지 못했어요.": "Couldn't start the session.",
  "세션 상태를 바꾸지 못했어요.": "Couldn't update the session.",
  "대표 메뉴 정보 준비 중": "Featured menu coming soon",
  "지역 정보 준비 중": "Location coming soon",
  "현재 위치 주변": "Near your location",
  "다음 라운드 →": "Next Round →",
  "선택한 식당": "Selected Restaurant",
  "프로필을 저장하지 못했어요.": "Couldn't save your profile.",
  "아바타를 변경했어요!": "Avatar updated!",
  "사진 업로드에 실패했어요.": "Couldn't upload the photo.",
  "프로필 사진을 저장하지 못했어요.": "Couldn't save your profile photo.",
  "Munchie 코스": "Munchie Course",
  "새 먼치맵": "New Munchie Map",
  "사진을 업로드하지 못했어요.": "Couldn't upload the photo.",
  "코스를 저장하지 못했어요.": "Couldn't save the course.",
  "사용자를 검색하지 못했습니다.": "Couldn't search users.",
  "세션 종료를 확인하지 못했어요.": "Couldn't confirm that the session ended.",
  "코스를 저장하지 못했습니다.": "Couldn't save the course.",
  "혼밥 코스": "Solo Dining",
  "가성비 맛집": "Great Value",
  "옐로우 런치트레이": "Yellow Lunch Tray",
  "Munchie 커뮤니티": "Munchie Community",
  평판: "Reputation",
  "맥락 적합": "Context Fit",
  "개인 취향": "Personal Taste",
  "최근 노출": "Recent Exposure",
  재소비: "Repeat Visits",
  "여정 연쇄": "Journey Sequence",
  "운영 지표는 관리자 대시보드에서만 볼 수 있습니다.":
    "Operational metrics are available only in the admin dashboard.",
  "검색어는 1~40자로 입력해 주세요.": "Enter a search term of 1–40 characters.",
  "사용자 정보가 올바르지 않습니다.": "Invalid user details.",
  "작성자 정보가 올바르지 않습니다.": "Invalid author details.",
};

// Keep legacy category identifiers unchanged at storage and filtering boundaries.
export function englishText<T>(value: T): T {
  if (typeof value !== "string") return value;
  const key = value.trim();
  const translated = englishCopy[key];
  if (
    !Object.prototype.hasOwnProperty.call(englishCopy, key) ||
    typeof translated !== "string"
  )
    return value;
  return value.replace(key, translated) as T;
}
